/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view_Pesquisar;

import bean.Dj_compras;
import dao.DJ_ClientesDAO;
import dao.DJ_ComprasDAO;
import view.JDlg_DJ_Compras;
import view_Controller.DJ_Controller_Compras;
import java.util.List;
import tools.Util;
/**
 *
 * @author danie
 */
public class JDlg_DJ_ComprasPesquisar extends javax.swing.JDialog {

    private JDlg_DJ_Compras jDlg_DJ_Compras;
    DJ_Controller_Compras dJ_Controller_Compras;
    /**
     * Creates new form JDlg_DJ_VendedorPesquisar
     */
    public JDlg_DJ_ComprasPesquisar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tabela de Vendedor");
        setLocationRelativeTo(null);
        dJ_Controller_Compras = new DJ_Controller_Compras();
        DJ_ComprasDAO dJ_ComprasDAO = new DJ_ComprasDAO();
        List lista = (List) dJ_ComprasDAO.listAll();
        dJ_Controller_Compras.setList(lista);
        jTbl_DJ_Compras.setModel(dJ_Controller_Compras);
    }
    
    public void SetTelaPai(JDlg_DJ_Compras jDlg_DJ_Compras){
        this.jDlg_DJ_Compras = jDlg_DJ_Compras;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_DJ_Compras = new javax.swing.JTable();
        jBtn_DJ_OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTbl_DJ_Compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTbl_DJ_Compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_DJ_ComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbl_DJ_Compras);

        jBtn_DJ_OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ok-24.png"))); // NOI18N
        jBtn_DJ_OK.setText("OK");
        jBtn_DJ_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtn_DJ_OK)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtn_DJ_OK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_DJ_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_OKActionPerformed
        // TODO add your handling code here:
        if(jTbl_DJ_Compras.getSelectedRow() == -1){
            Util.mensagem("Não esttá selecionado nadie");
        }else {
        Dj_compras dj_compras = dJ_Controller_Compras.getBean( jTbl_DJ_Compras.getSelectedRow() );
        jDlg_DJ_Compras.beanView(dj_compras);
        this.setVisible(false);
        }
    }//GEN-LAST:event_jBtn_DJ_OKActionPerformed

    private void jTbl_DJ_ComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_DJ_ComprasMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            
        jBtn_DJ_OKActionPerformed(null);
        }
    }//GEN-LAST:event_jTbl_DJ_ComprasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_ComprasPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_ComprasPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_ComprasPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_ComprasPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_DJ_ComprasPesquisar dialog = new JDlg_DJ_ComprasPesquisar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_DJ_OK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbl_DJ_Compras;
    // End of variables declaration//GEN-END:variables
}
