/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DJ_ComprasDAO;
import bean.Dj_compras;
import bean.Dj_produtos;
import dao.DJ_ProdutosDAO;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jfree.data.category.CategoryDataset;
import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
/**
 *
 * @author u11200121120
 */
public class JDlg_DJ_GraficosProdutos extends javax.swing.JDialog {

    /**
     * Creates new form JDlg_DJ_Graficos_Produtos
     */
    public JDlg_DJ_GraficosProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Gráfico");
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 32));
        jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 32));
        setLocationRelativeTo(null);
        //tentei não consigui fazer a funcionalidade extra
        DJ_ProdutosDAO dao = new DJ_ProdutosDAO();
        List<Dj_produtos> lista = (List<Dj_produtos>) dao.listAll();

        // Gera mapas
        Map<String, Integer> mapaMaterial = contarPorMaterial(lista);
        Map<Double,Integer> mapaAvaliacao = contarPorAvaliacao(lista);

        // Gera datasets
        PieDataset datasetMaterial = criarDatasetPorMaterial(mapaMaterial);
        CategoryDataset datasetAvaliacao = criarDatasetPorAvaliacao(mapaAvaliacao);


        // Cria gráficos
        JFreeChart grafMaterial = criarGraficoMaterial(datasetMaterial);
        JFreeChart grafAvaliacao = criarGraficoAvaliacao(datasetAvaliacao);

        // Cria paineis
        ChartPanel painel1 = new ChartPanel(grafMaterial);
        ChartPanel painel2 = new ChartPanel(grafAvaliacao);

        // Layout
        setLayout(new GridLayout(1, 2));
        add(painel1);
        add(painel2);
    }
    
    
    
    
    //Agrupação do Material e da Avaliação
    public Map<String, Integer> contarPorMaterial(List<Dj_produtos> lista) {
        Map<String, Integer> mapa = new HashMap<>();

        for (Dj_produtos p : lista) {
            mapa.put(p.getDj_material(),
                mapa.getOrDefault(p.getDj_material(), 0) + 1
            );
        }

        return mapa;
    }
    public Map<Double, Integer> contarPorAvaliacao(List<Dj_produtos> lista) {
    Map<Double, Integer> mapa = new HashMap<>();

    for (Dj_produtos p : lista) {
        mapa.put(p.getDj_avaliacao(),
            mapa.getOrDefault(p.getDj_avaliacao(), 0) + 1
            );
        }

        return mapa;
    }

    
    
    
    //Criação de Dataset para Material e para Avaliação
    public PieDataset criarDatasetPorMaterial(Map<String, Integer> mapa) {
        DefaultPieDataset dataset = new DefaultPieDataset();

        for (Map.Entry<String, Integer> entry : mapa.entrySet()) {
            dataset.setValue(entry.getKey(), entry.getValue());
        }

        return dataset;
    }
    public CategoryDataset criarDatasetPorAvaliacao(Map<Double,Integer> mapa) {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    for (Map.Entry<Double,Integer> entry : mapa.entrySet()) {
        dataset.addValue(entry.getValue(), "Quantidade", entry.getKey());
    }

    return dataset;
}

    
    
    //Criação do gráfico de Pizza e de Barra
    public JFreeChart criarGraficoMaterial(PieDataset dataset) { 
    return ChartFactory.createPieChart(
        "Produtos por Material",
        dataset,
        true,
        true,
        false
        );
    }
    
    public JFreeChart criarGraficoAvaliacao(CategoryDataset dataset) {
    return ChartFactory.createBarChart(
        "Produtos por Avaliação",
        "Avaliação",
        "Quantidade",
        dataset
        );
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl_Grafico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Gráficos de Pizza");

        jLabel2.setText("Gráfico de Barra");

        javax.swing.GroupLayout jPnl_GraficoLayout = new javax.swing.GroupLayout(jPnl_Grafico);
        jPnl_Grafico.setLayout(jPnl_GraficoLayout);
        jPnl_GraficoLayout.setHorizontalGroup(
            jPnl_GraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_GraficoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_GraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(720, Short.MAX_VALUE))
        );
        jPnl_GraficoLayout.setVerticalGroup(
            jPnl_GraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_GraficoLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addComponent(jLabel2)
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl_Grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl_Grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_GraficosProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_GraficosProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_GraficosProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_GraficosProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_DJ_GraficosProdutos dialog = new JDlg_DJ_GraficosProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPnl_Grafico;
    // End of variables declaration//GEN-END:variables
}
