/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.DjProdutos;
import tools.Util;
import view_Pesquisar.JDlg_DJ_ProdutosPesquisar;
import dao.DJ_ProdutosDAO;
/**
 *
 * @author danie
 */
public class JDlg_DJ_Produtos extends javax.swing.JDialog {

    private boolean incluir;
    /**
     * Creates new form JDlg_DJ_Produtos
     */
    public JDlg_DJ_Produtos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Produtos");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxt_DJ_Nome, jTxt_DJ_Codigo, jTxt_DJ_Descricao, jTxt_DJ_Material,
                jTxt_DJ_NomeFlor, jTxt_DJ_Preco, jFmt_DJ_Avaliacao, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
    }
    
    public DjProdutos viewBean(){
        DjProdutos djProdutos = new DjProdutos();
        djProdutos.setDjIdProdutos(Util.strToInt(jTxt_DJ_Codigo.getText()));
        djProdutos.setDjNome((jTxt_DJ_Nome.getText()));
        djProdutos.setDjAvaliacao(Util.strToDouble(jFmt_DJ_Avaliacao.getText()));
        djProdutos.setDjDescricao((jTxt_DJ_Descricao.getText()));
        djProdutos.setDjMaterial((jTxt_DJ_Material.getText()));
        djProdutos.setDjNomeDaFlor((jTxt_DJ_NomeFlor.getText()));
        djProdutos.setDjPreco(Util.strToDouble(jTxt_DJ_Preco.getText()));
        return djProdutos;
    }
    
    public void beanView(DjProdutos djProdutos){
        jTxt_DJ_Codigo.setText(Util.intToStr(djProdutos.getDjIdProdutos()));
        jTxt_DJ_Descricao.setText((djProdutos.getDjDescricao()));
        jTxt_DJ_Material.setText((djProdutos.getDjMaterial()));
        jTxt_DJ_Nome.setText((djProdutos.getDjNome()));
        jTxt_DJ_NomeFlor.setText((djProdutos.getDjNomeDaFlor()));
        jTxt_DJ_Preco.setText(Util.DoubleToStr(djProdutos.getDjPreco()));
        jFmt_DJ_Avaliacao.setText(Util.DoubleToStr(djProdutos.getDjAvaliacao()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_DJ_Cancelar = new javax.swing.JButton();
        jBtn_DJ_Pesquisar = new javax.swing.JButton();
        jBtn_DJ_Incluir = new javax.swing.JButton();
        jBtn_DJ_Alterar = new javax.swing.JButton();
        jBtn_DJ_Excluir = new javax.swing.JButton();
        jBtn_DJ_Confirmar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jFmt_DJ_Avaliacao = new javax.swing.JFormattedTextField();
        jTxt_DJ_Preco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxt_DJ_Material = new javax.swing.JTextField();
        jTxt_DJ_Codigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxt_DJ_Nome = new javax.swing.JTextField();
        jTxt_DJ_Descricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxt_DJ_NomeFlor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtn_DJ_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancelar-24.png"))); // NOI18N
        jBtn_DJ_Cancelar.setText("Cancelar");
        jBtn_DJ_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_CancelarActionPerformed(evt);
            }
        });

        jBtn_DJ_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-24.png"))); // NOI18N
        jBtn_DJ_Pesquisar.setText("Pesquisar");
        jBtn_DJ_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_PesquisarActionPerformed(evt);
            }
        });

        jBtn_DJ_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mais-24.png"))); // NOI18N
        jBtn_DJ_Incluir.setText("Incluir");
        jBtn_DJ_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_IncluirActionPerformed(evt);
            }
        });

        jBtn_DJ_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-alter-24.png"))); // NOI18N
        jBtn_DJ_Alterar.setText("Alterar");
        jBtn_DJ_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_AlterarActionPerformed(evt);
            }
        });

        jBtn_DJ_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-entrada-proibida-24.png"))); // NOI18N
        jBtn_DJ_Excluir.setText("Excluir");
        jBtn_DJ_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_ExcluirActionPerformed(evt);
            }
        });

        jBtn_DJ_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-botão-de-opção-marcado-24.png"))); // NOI18N
        jBtn_DJ_Confirmar.setText("Confirmar");
        jBtn_DJ_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_ConfirmarActionPerformed(evt);
            }
        });

        jLabel5.setText("Avaliação");

        try {
            jFmt_DJ_Avaliacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Preço");

        jLabel7.setText("Material");

        jLabel1.setText("Código");

        jLabel4.setText("Descrição");

        jLabel2.setText("Nome");

        jLabel6.setText("Nome da Flor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt_DJ_Codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtn_DJ_Incluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtn_DJ_Alterar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtn_DJ_Excluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtn_DJ_Confirmar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtn_DJ_Cancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtn_DJ_Pesquisar))
                                    .addComponent(jTxt_DJ_Material)
                                    .addComponent(jTxt_DJ_Descricao))
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxt_DJ_Preco, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addComponent(jTxt_DJ_Nome))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(263, 263, 263))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTxt_DJ_NomeFlor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmt_DJ_Avaliacao))
                                .addGap(11, 11, 11))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_DJ_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxt_DJ_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxt_DJ_NomeFlor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmt_DJ_Avaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_DJ_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_DJ_Material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_DJ_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_DJ_Incluir)
                    .addComponent(jBtn_DJ_Alterar)
                    .addComponent(jBtn_DJ_Excluir)
                    .addComponent(jBtn_DJ_Confirmar)
                    .addComponent(jBtn_DJ_Cancelar)
                    .addComponent(jBtn_DJ_Pesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_DJ_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_IncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxt_DJ_Nome, jTxt_DJ_Codigo, jTxt_DJ_Descricao, jTxt_DJ_Material,
                jTxt_DJ_NomeFlor, jTxt_DJ_Preco, jFmt_DJ_Avaliacao, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(false, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir);
        
        Util.limpar(jTxt_DJ_Nome, jTxt_DJ_Codigo, jTxt_DJ_Descricao, jTxt_DJ_Material,
                jTxt_DJ_NomeFlor, jTxt_DJ_Preco, jFmt_DJ_Avaliacao);
        
        jTxt_DJ_Codigo.grabFocus();
        
        incluir = true;
    }//GEN-LAST:event_jBtn_DJ_IncluirActionPerformed

    private void jBtn_DJ_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_AlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxt_DJ_Nome, jTxt_DJ_Descricao, jTxt_DJ_Material,
                jTxt_DJ_NomeFlor, jTxt_DJ_Preco, jFmt_DJ_Avaliacao, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(false, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir, jTxt_DJ_Codigo);
        
        jTxt_DJ_Nome.grabFocus();
        
        incluir = false;
    }//GEN-LAST:event_jBtn_DJ_AlterarActionPerformed

    private void jBtn_DJ_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_ConfirmarActionPerformed
        // TODO add your handling code here:
        DJ_ProdutosDAO dJ_ProdutosDAO = new DJ_ProdutosDAO();
        
        if(incluir == true){
            dJ_ProdutosDAO.insert(viewBean());
        }else{
            dJ_ProdutosDAO.update(viewBean());
        }
        
        Util.habilitar(false, jTxt_DJ_Nome, jTxt_DJ_Descricao, jTxt_DJ_Material, jTxt_DJ_Codigo,
                jTxt_DJ_NomeFlor, jTxt_DJ_Preco, jFmt_DJ_Avaliacao, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(true, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir);
        
        Util.limpar(jTxt_DJ_Nome, jTxt_DJ_Codigo, jTxt_DJ_Descricao, jTxt_DJ_Material,
                jTxt_DJ_NomeFlor, jTxt_DJ_Preco, jFmt_DJ_Avaliacao);
    }//GEN-LAST:event_jBtn_DJ_ConfirmarActionPerformed

    private void jBtn_DJ_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_CancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxt_DJ_Nome, jTxt_DJ_Descricao, jTxt_DJ_Material, jTxt_DJ_Codigo,
                jTxt_DJ_NomeFlor, jTxt_DJ_Preco, jFmt_DJ_Avaliacao, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(true, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir);
        
        Util.limpar(jTxt_DJ_Nome, jTxt_DJ_Codigo, jTxt_DJ_Descricao, jTxt_DJ_Material,
                jTxt_DJ_NomeFlor, jTxt_DJ_Preco, jFmt_DJ_Avaliacao);
    }//GEN-LAST:event_jBtn_DJ_CancelarActionPerformed

    private void jBtn_DJ_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_ExcluirActionPerformed
        // TODO add your handling code here:
        if(Util.perguntar("Deseja Excluir?")){
            DJ_ProdutosDAO dJ_ProdutosDAO = new DJ_ProdutosDAO();
            dJ_ProdutosDAO.delete(viewBean());
            Util.mensagem("Exluido com sucesso!");
        } else {
            Util.mensagem("Exclusão cancelada!");
        }
            Util.limpar(jTxt_DJ_Nome, jTxt_DJ_Codigo, jTxt_DJ_Descricao, jTxt_DJ_Material,
                jTxt_DJ_NomeFlor, jTxt_DJ_Preco, jFmt_DJ_Avaliacao);
    }//GEN-LAST:event_jBtn_DJ_ExcluirActionPerformed

    private void jBtn_DJ_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_ProdutosPesquisar jDlg_DJ_ProdutosPesquisar = new JDlg_DJ_ProdutosPesquisar(null, true);
        jDlg_DJ_ProdutosPesquisar.setTelaPai(this);
        jDlg_DJ_ProdutosPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtn_DJ_PesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_DJ_Produtos dialog = new JDlg_DJ_Produtos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_DJ_Alterar;
    private javax.swing.JButton jBtn_DJ_Cancelar;
    private javax.swing.JButton jBtn_DJ_Confirmar;
    private javax.swing.JButton jBtn_DJ_Excluir;
    private javax.swing.JButton jBtn_DJ_Incluir;
    private javax.swing.JButton jBtn_DJ_Pesquisar;
    private javax.swing.JFormattedTextField jFmt_DJ_Avaliacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTxt_DJ_Codigo;
    private javax.swing.JTextField jTxt_DJ_Descricao;
    private javax.swing.JTextField jTxt_DJ_Material;
    private javax.swing.JTextField jTxt_DJ_Nome;
    private javax.swing.JTextField jTxt_DJ_NomeFlor;
    private javax.swing.JTextField jTxt_DJ_Preco;
    // End of variables declaration//GEN-END:variables
}
