/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Dj_compras;
import bean.Dj_fornecedor;
import bean.Dj_usuarios;
import java.util.List;
import tools.Util;
import dao.DJ_UsuariosDAO;
import dao.DJ_FornecedorDAO;
import dao.DJ_ComprasDAO;
import dao.DJ_ComprasProdutosDAO;
import java.util.ArrayList;
import view_Controller.DJ_Controller_ComprasProdutos;
import view_Pesquisar.JDlg_DJ_ComprasPesquisar;
/**
 *
 * @author u11200121120
 */
public class JDlg_DJ_Compras extends javax.swing.JDialog {
    private boolean incluir;
    DJ_Controller_ComprasProdutos dJ_Controller_ComprasProdutos;
    /**
     * Creates new form JDlg_DJ_Compras
     */
    public JDlg_DJ_Compras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Movimento de Compras");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxt_DJ_Codigo, jTxt_DJ_Total, jFmt_DJ_DataCompras, jCbo_DJ_Fornecedor, jCbo_DJ_Usuarios,
                jBtn_DJ_Cancelar, jBtn_DJ_Confirmar, jBtn_DJ_AlterarProd, jBtn_DJ_ExcluirProd, jBtn_DJ_IncluirProd, 
                jTbl_DJ_Compras);
        DJ_UsuariosDAO dJ_UsuariosDAO = new DJ_UsuariosDAO();
        DJ_FornecedorDAO dJ_FornecedorDAO = new DJ_FornecedorDAO();
     
        List usuarios = (List) dJ_UsuariosDAO.listAll();
        List fornecedor = (List) dJ_FornecedorDAO.listAll();
        for (int i = 0; i < usuarios.size(); i++) {
            jCbo_DJ_Usuarios.addItem((Dj_usuarios) usuarios.get(i));
            
        }
        for (int i = 0; i < fornecedor.size(); i++) {
            jCbo_DJ_Fornecedor.addItem((Dj_fornecedor) fornecedor.get(i));
            
        }
        dJ_Controller_ComprasProdutos = new DJ_Controller_ComprasProdutos();
        dJ_Controller_ComprasProdutos.setList(new ArrayList());
        jTbl_DJ_Compras.setModel(dJ_Controller_ComprasProdutos);
    }
    
    
    public Dj_compras viewBean(){
        Dj_compras dj_compras = new Dj_compras();
        dj_compras.setDj_idCompras(Util.strToInt(jTxt_DJ_Codigo.getText()));
        dj_compras.setDj_dataCompras(Util.strToDate(jFmt_DJ_DataCompras.getText()));
        dj_compras.setDj_fkUsuarios ((Dj_usuarios) jCbo_DJ_Usuarios.getSelectedItem());
        dj_compras.setDj_fkFornecedor((Dj_fornecedor) jCbo_DJ_Fornecedor.getSelectedItem());
        dj_compras.setDj_total(Util.strToDouble(jTxt_DJ_Total.getText())); 
        return dj_compras;
    }
    public void beanView(Dj_compras dj_compras){
        jTxt_DJ_Codigo.setText(Util.intToStr(dj_compras.getDj_idCompras()));
        jFmt_DJ_DataCompras.setText(Util.datetoStr(dj_compras.getDj_dataCompras()));
        jCbo_DJ_Usuarios.setSelectedItem((dj_compras.getDj_fkUsuarios()));
        jCbo_DJ_Fornecedor.setSelectedItem((dj_compras.getDj_fkFornecedor()));
        jTxt_DJ_Total.setText(Util.DoubleToStr(dj_compras.getDj_total()));
        DJ_ComprasProdutosDAO dJ_ComprasProdutosDAO = new DJ_ComprasProdutosDAO();
        List lista = (List) dJ_ComprasProdutosDAO.listProdutos(dj_compras);
        dJ_Controller_ComprasProdutos.setList(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxt_DJ_Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCbo_DJ_Usuarios = new javax.swing.JComboBox<Dj_usuarios>();
        jCbo_DJ_Fornecedor = new javax.swing.JComboBox<Dj_fornecedor>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxt_DJ_Total = new javax.swing.JTextField();
        jFmt_DJ_DataCompras = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_DJ_Compras = new javax.swing.JTable();
        jBtn_DJ_Alterar = new javax.swing.JButton();
        jBtn_DJ_Excluir = new javax.swing.JButton();
        jBtn_DJ_Confirmar = new javax.swing.JButton();
        jBtn_DJ_Cancelar = new javax.swing.JButton();
        jBtn_DJ_Pesquisar = new javax.swing.JButton();
        jBtn_DJ_Incluir = new javax.swing.JButton();
        jBtn_DJ_IncluirProd = new javax.swing.JButton();
        jBtn_DJ_AlterarProd = new javax.swing.JButton();
        jBtn_DJ_ExcluirProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jTxt_DJ_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_DJ_CodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data de Compras");

        jLabel3.setText("Fornecedor");

        jLabel4.setText("Usuários");

        jLabel5.setText("Total");

        jTxt_DJ_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_DJ_TotalActionPerformed(evt);
            }
        });

        try {
            jFmt_DJ_DataCompras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTbl_DJ_Compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTbl_DJ_Compras);

        jBtn_DJ_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-alter-24.png"))); // NOI18N
        jBtn_DJ_Alterar.setText("Alterar");
        jBtn_DJ_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_AlterarActionPerformed(evt);
            }
        });

        jBtn_DJ_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-entrada-proibida-24.png"))); // NOI18N
        jBtn_DJ_Excluir.setText("Excluir");
        jBtn_DJ_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_ExcluirActionPerformed(evt);
            }
        });

        jBtn_DJ_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-botão-de-opção-marcado-24.png"))); // NOI18N
        jBtn_DJ_Confirmar.setText("Confirmar");
        jBtn_DJ_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_ConfirmarActionPerformed(evt);
            }
        });

        jBtn_DJ_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancelar-24.png"))); // NOI18N
        jBtn_DJ_Cancelar.setText("Cancelar");
        jBtn_DJ_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_CancelarActionPerformed(evt);
            }
        });

        jBtn_DJ_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-24.png"))); // NOI18N
        jBtn_DJ_Pesquisar.setText("Pesquisar");
        jBtn_DJ_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_PesquisarActionPerformed(evt);
            }
        });

        jBtn_DJ_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mais-24.png"))); // NOI18N
        jBtn_DJ_Incluir.setText("Incluir");
        jBtn_DJ_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_IncluirActionPerformed(evt);
            }
        });

        jBtn_DJ_IncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mais-24.png"))); // NOI18N
        jBtn_DJ_IncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_IncluirProdActionPerformed(evt);
            }
        });

        jBtn_DJ_AlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-alter-24.png"))); // NOI18N
        jBtn_DJ_AlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_AlterarProdActionPerformed(evt);
            }
        });

        jBtn_DJ_ExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-entrada-proibida-24.png"))); // NOI18N
        jBtn_DJ_ExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_ExcluirProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn_DJ_Incluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Confirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Pesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxt_DJ_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmt_DJ_DataCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCbo_DJ_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCbo_DJ_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTxt_DJ_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn_DJ_AlterarProd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtn_DJ_ExcluirProd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtn_DJ_IncluirProd, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCbo_DJ_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_DJ_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxt_DJ_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmt_DJ_DataCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbo_DJ_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jBtn_DJ_IncluirProd)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_DJ_AlterarProd)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_DJ_ExcluirProd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_DJ_Incluir)
                    .addComponent(jBtn_DJ_Alterar)
                    .addComponent(jBtn_DJ_Excluir)
                    .addComponent(jBtn_DJ_Confirmar)
                    .addComponent(jBtn_DJ_Cancelar)
                    .addComponent(jBtn_DJ_Pesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_DJ_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_DJ_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_DJ_CodigoActionPerformed

    private void jBtn_DJ_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_AlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxt_DJ_Codigo, jTxt_DJ_Total, jFmt_DJ_DataCompras, jCbo_DJ_Fornecedor, jCbo_DJ_Usuarios,
                jBtn_DJ_Cancelar, jBtn_DJ_Confirmar, jBtn_DJ_AlterarProd, jBtn_DJ_ExcluirProd, jBtn_DJ_IncluirProd, 
                jTbl_DJ_Compras);

        Util.habilitar(false, jBtn_DJ_Alterar, jBtn_DJ_Excluir, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jTxt_DJ_Codigo);

        jFmt_DJ_DataCompras.grabFocus();

        incluir = false;

    }//GEN-LAST:event_jBtn_DJ_AlterarActionPerformed

    private void jBtn_DJ_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_ExcluirActionPerformed
        // TODO add your handling code here:
        if(Util.perguntar("Deseja Excluir?")){
            DJ_ComprasDAO dJ_ComprasDAO = new DJ_ComprasDAO();
            dJ_ComprasDAO.delete(viewBean());
            Util.mensagem("Exluido com sucesso!");
        } else {
            Util.mensagem("Exclusão cancelada!");
        }
        Util.limpar( jTxt_DJ_Codigo, jTxt_DJ_Total, jFmt_DJ_DataCompras, jCbo_DJ_Fornecedor, jCbo_DJ_Usuarios);
    }//GEN-LAST:event_jBtn_DJ_ExcluirActionPerformed

    private void jBtn_DJ_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_ConfirmarActionPerformed
        // TODO add your handling code here:
        DJ_ComprasDAO dJ_ComprasDAO = new DJ_ComprasDAO();

        if(incluir == true){
            dJ_ComprasDAO.insert(viewBean());
        }else{
            dJ_ComprasDAO.update(viewBean());
        }

        Util.habilitar(false, jTxt_DJ_Codigo, jTxt_DJ_Total, jFmt_DJ_DataCompras, jCbo_DJ_Fornecedor, jCbo_DJ_Usuarios,
                jBtn_DJ_Cancelar, jBtn_DJ_Confirmar, jBtn_DJ_AlterarProd, jBtn_DJ_ExcluirProd, jBtn_DJ_IncluirProd, 
                jTbl_DJ_Compras);
        
        Util.habilitar(true, jBtn_DJ_Alterar, jBtn_DJ_Excluir, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir);

        Util.limpar( jTxt_DJ_Codigo, jTxt_DJ_Total, jFmt_DJ_DataCompras, jCbo_DJ_Fornecedor, jCbo_DJ_Usuarios);
    }//GEN-LAST:event_jBtn_DJ_ConfirmarActionPerformed

    private void jBtn_DJ_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_CancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxt_DJ_Codigo, jTxt_DJ_Total, jFmt_DJ_DataCompras, jCbo_DJ_Fornecedor, jCbo_DJ_Usuarios,
                jBtn_DJ_Cancelar, jBtn_DJ_Confirmar, jBtn_DJ_AlterarProd, jBtn_DJ_ExcluirProd, jBtn_DJ_IncluirProd, 
                jTbl_DJ_Compras);

        Util.habilitar(true, jBtn_DJ_Alterar, jBtn_DJ_Excluir, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir);

        Util.limpar( jTxt_DJ_Codigo, jTxt_DJ_Total, jFmt_DJ_DataCompras, jCbo_DJ_Fornecedor, jCbo_DJ_Usuarios);
    }//GEN-LAST:event_jBtn_DJ_CancelarActionPerformed

    private void jBtn_DJ_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_ComprasPesquisar jDlg_DJ_ComprasPesquisar = new JDlg_DJ_ComprasPesquisar(null, true);
        jDlg_DJ_ComprasPesquisar.SetTelaPai(this);
        jDlg_DJ_ComprasPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtn_DJ_PesquisarActionPerformed

    private void jBtn_DJ_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_IncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxt_DJ_Codigo, jTxt_DJ_Total, jFmt_DJ_DataCompras, jCbo_DJ_Fornecedor, jCbo_DJ_Usuarios,
                jBtn_DJ_Cancelar, jBtn_DJ_Confirmar, jBtn_DJ_AlterarProd, jBtn_DJ_ExcluirProd, jBtn_DJ_IncluirProd, 
                jTbl_DJ_Compras);
//
        Util.habilitar(false, jBtn_DJ_Alterar, jBtn_DJ_Excluir, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir);

        Util.limpar( jTxt_DJ_Codigo, jTxt_DJ_Total, jFmt_DJ_DataCompras, jCbo_DJ_Fornecedor, jCbo_DJ_Usuarios);

        jTxt_DJ_Codigo.grabFocus();

        incluir = true;

    }//GEN-LAST:event_jBtn_DJ_IncluirActionPerformed

    private void jBtn_DJ_IncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_IncluirProdActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_ComprasProdutos jDlg_DJ_ComprasProdutos = new JDlg_DJ_ComprasProdutos(null, true);
        jDlg_DJ_ComprasProdutos.setVisible(true);
    }//GEN-LAST:event_jBtn_DJ_IncluirProdActionPerformed

    private void jBtn_DJ_AlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_AlterarProdActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_ComprasProdutos jDlg_DJ_ComprasProdutos = new JDlg_DJ_ComprasProdutos(null, true);
        jDlg_DJ_ComprasProdutos.setVisible(true);
    }//GEN-LAST:event_jBtn_DJ_AlterarProdActionPerformed

    private void jBtn_DJ_ExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_ExcluirProdActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_ComprasProdutos jDlg_DJ_ComprasProdutos = new JDlg_DJ_ComprasProdutos(null, true);
        jDlg_DJ_ComprasProdutos.setVisible(true);
    }//GEN-LAST:event_jBtn_DJ_ExcluirProdActionPerformed

    private void jTxt_DJ_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_DJ_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_DJ_TotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_DJ_Compras dialog = new JDlg_DJ_Compras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_DJ_Alterar;
    private javax.swing.JButton jBtn_DJ_AlterarProd;
    private javax.swing.JButton jBtn_DJ_Cancelar;
    private javax.swing.JButton jBtn_DJ_Confirmar;
    private javax.swing.JButton jBtn_DJ_Excluir;
    private javax.swing.JButton jBtn_DJ_ExcluirProd;
    private javax.swing.JButton jBtn_DJ_Incluir;
    private javax.swing.JButton jBtn_DJ_IncluirProd;
    private javax.swing.JButton jBtn_DJ_Pesquisar;
    private javax.swing.JComboBox<Dj_fornecedor> jCbo_DJ_Fornecedor;
    private javax.swing.JComboBox<Dj_usuarios> jCbo_DJ_Usuarios;
    private javax.swing.JFormattedTextField jFmt_DJ_DataCompras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbl_DJ_Compras;
    private javax.swing.JTextField jTxt_DJ_Codigo;
    private javax.swing.JTextField jTxt_DJ_Total;
    // End of variables declaration//GEN-END:variables
}
