/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Dj_compras;
import bean.Dj_compras_produtos;
import bean.Dj_produtos;
import dao.DJ_ProdutosDAO;
import view_Controller.DJ_Controller_ComprasProdutos;
import java.util.List;
import tools.Util;

/**
 *
 * @author danie
 */
public class JDlg_DJ_ComprasProdutos extends javax.swing.JDialog {

    JDlg_DJ_Compras jDlg_DJ_Compras;
    /**
     * Creates new form JDlg_DJ_ComprasProdutos
     */
    public JDlg_DJ_ComprasProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Tela de Movimento de Compras de Produtos");
            Util.habilitar(false, jTxt_DJ_ValorUnitario, jTxt_DJ_Total);
            jTxt_DJ_Quantidade.setText("1");
            DJ_ProdutosDAO produtosDAO = new DJ_ProdutosDAO();
            List lista = (List) produtosDAO.listAll();
            for (Object object : lista) {
                jCbo_DJ_Produtos.addItem((Dj_produtos) object);
            }

    }
        public void setTelaAnterior(JDlg_DJ_Compras jDlg_DJ_Compras){
            this.jDlg_DJ_Compras = jDlg_DJ_Compras;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBtn_DJ_OK = new javax.swing.JButton();
        jBtn_DJ_Cancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCbo_DJ_Produtos = new javax.swing.JComboBox<bean.Dj_produtos>();
        jLabel4 = new javax.swing.JLabel();
        jTxt_DJ_Quantidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxt_DJ_ValorUnitario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxt_DJ_Total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JBtn_DJ_OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ok-24.png"))); // NOI18N
        JBtn_DJ_OK.setText("OK");
        JBtn_DJ_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_DJ_OKActionPerformed(evt);
            }
        });

        jBtn_DJ_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancelar-24.png"))); // NOI18N
        jBtn_DJ_Cancelar.setText("Cancelar");
        jBtn_DJ_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_CancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Produtos");

        jCbo_DJ_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbo_DJ_ProdutosActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade");

        jTxt_DJ_Quantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxt_DJ_QuantidadeKeyReleased(evt);
            }
        });

        jLabel5.setText("Valor Unitário");

        jLabel6.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(JBtn_DJ_OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jBtn_DJ_Cancelar)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxt_DJ_Total, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbo_DJ_Produtos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxt_DJ_Quantidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt_DJ_ValorUnitario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jCbo_DJ_Produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jTxt_DJ_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_DJ_ValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_DJ_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtn_DJ_OK)
                    .addComponent(jBtn_DJ_Cancelar))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_DJ_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_DJ_OKActionPerformed
        // TODO add your handling code here:
        Dj_compras_produtos dj_compras_produtos = new Dj_compras_produtos();
        dj_compras_produtos.setDj_fkProdutos((Dj_produtos) jCbo_DJ_Produtos.getSelectedItem());
        dj_compras_produtos.setDj_quantidade(Util.strToInt(jTxt_DJ_Quantidade.getText()) );
        dj_compras_produtos.setDj_valor_unitario(Util.strToDouble(jTxt_DJ_ValorUnitario.getText()) );
        jDlg_DJ_Compras.dJ_Controller_ComprasProdutos.addBean(dj_compras_produtos);
        setVisible(false);
    }//GEN-LAST:event_JBtn_DJ_OKActionPerformed

    private void jBtn_DJ_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_CancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBtn_DJ_CancelarActionPerformed

    private void jCbo_DJ_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbo_DJ_ProdutosActionPerformed
        // TODO add your handling code here:
        Dj_produtos dj_produtos =  (Dj_produtos) jCbo_DJ_Produtos.getSelectedItem();
        jTxt_DJ_ValorUnitario.setText(Util.DoubleToStr(dj_produtos.getDj_preco()));
        int quant = Util.strToInt(jTxt_DJ_Quantidade.getText());
        jTxt_DJ_Total.setText(Util.DoubleToStr(quant*dj_produtos.getDj_preco()));
    }//GEN-LAST:event_jCbo_DJ_ProdutosActionPerformed

    private void jTxt_DJ_QuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_DJ_QuantidadeKeyReleased
        // TODO add your handling code here:
        if(jTxt_DJ_Quantidade.getText().isEmpty()){
            jTxt_DJ_Total.setText("");
        }else {
            Dj_produtos dj_produtos = (Dj_produtos) jCbo_DJ_Produtos.getSelectedItem();
            int quant = Util.strToInt(jTxt_DJ_Quantidade.getText());
            jTxt_DJ_Total.setText(Util.DoubleToStr(quant*dj_produtos.getDj_preco()));
        }
    }//GEN-LAST:event_jTxt_DJ_QuantidadeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_ComprasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_ComprasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_ComprasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_ComprasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_DJ_ComprasProdutos dialog = new JDlg_DJ_ComprasProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_DJ_OK;
    private javax.swing.JButton jBtn_DJ_Cancelar;
    private javax.swing.JComboBox<bean.Dj_produtos> jCbo_DJ_Produtos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTxt_DJ_Quantidade;
    private javax.swing.JTextField jTxt_DJ_Total;
    private javax.swing.JTextField jTxt_DJ_ValorUnitario;
    // End of variables declaration//GEN-END:variables
}
