/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import tools.Util;
import view_Pesquisar.JDlg_DJ_FornecedorPesquisar;
/**
 *
 * @author danie
 */
public class JDlg_DJ_Fornecedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlg_DJ_Fornecedor
     */
    public JDlg_DJ_Fornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Fornecedor");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxt_DJ_Bairro, jTxt_DJ_Cidade, jTxt_DJ_Codigo, jTxt_DJ_Email, jTxt_DJ_Endereco, jTxt_DJ_Estado,
                jTxt_DJ_Nome, jTxt_DJ_NomeSite, jTxt_DJ_Pais, jFmt_DJ_Rg, jFmt_DJ_Telefone, jFmt_DJ_Cep, jFmt_DJ_Cnpj,
                jFmt_DJ_DataCadastro, jFmt_DJ_DataNascimento, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_DJ_Cancelar = new javax.swing.JButton();
        jBtn_DJ_Pesquisar = new javax.swing.JButton();
        jBtn_DJ_Incluir = new javax.swing.JButton();
        jBtn_DJ_Alterar = new javax.swing.JButton();
        jBtn_DJ_Excluir = new javax.swing.JButton();
        jBtn_DJ_Confirmar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jFmt_DJ_Cep = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jFmt_DJ_Telefone = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jFmt_DJ_Cnpj = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jFmt_DJ_Rg = new javax.swing.JFormattedTextField();
        jFmt_DJ_DataNascimento = new javax.swing.JFormattedTextField();
        jFmt_DJ_DataCadastro = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxt_DJ_Endereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxt_DJ_Cidade = new javax.swing.JTextField();
        jTxt_DJ_Codigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTxt_DJ_Pais = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxt_DJ_Nome = new javax.swing.JTextField();
        jTxt_DJ_Bairro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxt_DJ_NomeSite = new javax.swing.JTextField();
        jTxt_DJ_Estado = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTxt_DJ_Email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtn_DJ_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancelar-24.png"))); // NOI18N
        jBtn_DJ_Cancelar.setText("Cancelar");
        jBtn_DJ_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_CancelarActionPerformed(evt);
            }
        });

        jBtn_DJ_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-24.png"))); // NOI18N
        jBtn_DJ_Pesquisar.setText("Pesquisar");
        jBtn_DJ_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_PesquisarActionPerformed(evt);
            }
        });

        jBtn_DJ_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mais-24.png"))); // NOI18N
        jBtn_DJ_Incluir.setText("Incluir");
        jBtn_DJ_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_IncluirActionPerformed(evt);
            }
        });

        jBtn_DJ_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-alter-24.png"))); // NOI18N
        jBtn_DJ_Alterar.setText("Alterar");
        jBtn_DJ_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_AlterarActionPerformed(evt);
            }
        });

        jBtn_DJ_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-entrada-proibida-24.png"))); // NOI18N
        jBtn_DJ_Excluir.setText("Excluir");
        jBtn_DJ_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_ExcluirActionPerformed(evt);
            }
        });

        jBtn_DJ_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-botão-de-opção-marcado-24.png"))); // NOI18N
        jBtn_DJ_Confirmar.setText("Confirmar");
        jBtn_DJ_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_ConfirmarActionPerformed(evt);
            }
        });

        jLabel8.setText("CEP");

        jFmt_DJ_Cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel19.setText("Telefone");

        jFmt_DJ_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel20.setText("RG");

        jLabel22.setText("CNPJ");

        jFmt_DJ_Cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel1.setText("Data de nascimento");

        jFmt_DJ_Rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmt_DJ_RgActionPerformed(evt);
            }
        });

        jFmt_DJ_DataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jFmt_DJ_DataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel6.setText("Endereço");

        jLabel7.setText("Data de Cadastro");

        jLabel3.setText("Cidade");

        jLabel5.setText("País");

        jLabel18.setText("Código");

        jLabel15.setText("Nome");

        jLabel2.setText("Bairro");

        jLabel16.setText("Nome do Site");

        jLabel4.setText("Estado");

        jTxt_DJ_NomeSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_DJ_NomeSiteActionPerformed(evt);
            }
        });

        jLabel21.setText("E-mail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmt_DJ_Cep)
                    .addComponent(jTxt_DJ_Codigo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFmt_DJ_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmt_DJ_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jFmt_DJ_Rg)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxt_DJ_Nome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxt_DJ_Email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmt_DJ_Telefone)
                            .addComponent(jTxt_DJ_NomeSite)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel19))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxt_DJ_Bairro, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxt_DJ_Pais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt_DJ_Cidade)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxt_DJ_Estado)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFmt_DJ_DataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxt_DJ_Endereco))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn_DJ_Incluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Confirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Pesquisar))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(143, 143, 143)
                                .addComponent(jLabel6))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_DJ_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_DJ_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_DJ_NomeSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_DJ_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmt_DJ_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmt_DJ_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmt_DJ_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmt_DJ_Rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmt_DJ_DataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_DJ_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxt_DJ_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxt_DJ_Cidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxt_DJ_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxt_DJ_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmt_DJ_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_DJ_Incluir)
                    .addComponent(jBtn_DJ_Alterar)
                    .addComponent(jBtn_DJ_Excluir)
                    .addComponent(jBtn_DJ_Confirmar)
                    .addComponent(jBtn_DJ_Cancelar)
                    .addComponent(jBtn_DJ_Pesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFmt_DJ_RgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmt_DJ_RgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmt_DJ_RgActionPerformed

    private void jTxt_DJ_NomeSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_DJ_NomeSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_DJ_NomeSiteActionPerformed

    private void jBtn_DJ_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_IncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxt_DJ_Bairro, jTxt_DJ_Cidade, jTxt_DJ_Codigo, jTxt_DJ_Email, jTxt_DJ_Endereco, jTxt_DJ_Estado,
                jTxt_DJ_Nome, jTxt_DJ_NomeSite, jTxt_DJ_Pais, jFmt_DJ_Rg, jFmt_DJ_Telefone, jFmt_DJ_Cep, jFmt_DJ_Cnpj,
                jFmt_DJ_DataCadastro, jFmt_DJ_DataNascimento, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(false, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir);
        
        Util.limpar(jTxt_DJ_Bairro, jTxt_DJ_Cidade, jTxt_DJ_Codigo, jTxt_DJ_Email, jTxt_DJ_Endereco, jTxt_DJ_Estado,
                jTxt_DJ_Nome, jTxt_DJ_NomeSite, jTxt_DJ_Pais, jFmt_DJ_Rg, jFmt_DJ_Telefone, jFmt_DJ_Cep, jFmt_DJ_Cnpj,
                jFmt_DJ_DataCadastro, jFmt_DJ_DataNascimento);
        
        jTxt_DJ_Codigo.grabFocus();
    }//GEN-LAST:event_jBtn_DJ_IncluirActionPerformed

    private void jBtn_DJ_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_AlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxt_DJ_Bairro, jTxt_DJ_Cidade, jTxt_DJ_Email, jTxt_DJ_Endereco, jTxt_DJ_Estado,
                jTxt_DJ_Nome, jTxt_DJ_NomeSite, jTxt_DJ_Pais, jFmt_DJ_Rg, jFmt_DJ_Telefone, jFmt_DJ_Cep, jFmt_DJ_Cnpj,
                jFmt_DJ_DataCadastro, jFmt_DJ_DataNascimento, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(false, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir, jTxt_DJ_Codigo);
        
        jTxt_DJ_Nome.grabFocus();
    }//GEN-LAST:event_jBtn_DJ_AlterarActionPerformed

    private void jBtn_DJ_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_ConfirmarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxt_DJ_Bairro, jTxt_DJ_Cidade, jTxt_DJ_Codigo, jTxt_DJ_Email, jTxt_DJ_Endereco, jTxt_DJ_Estado,
                jTxt_DJ_Nome, jTxt_DJ_NomeSite, jTxt_DJ_Pais, jFmt_DJ_Rg, jFmt_DJ_Telefone, jFmt_DJ_Cep, jFmt_DJ_Cnpj,
                jFmt_DJ_DataCadastro, jFmt_DJ_DataNascimento, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(true, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir);
        
        Util.limpar(jTxt_DJ_Bairro, jTxt_DJ_Cidade, jTxt_DJ_Codigo, jTxt_DJ_Email, jTxt_DJ_Endereco, jTxt_DJ_Estado,
                jTxt_DJ_Nome, jTxt_DJ_NomeSite, jTxt_DJ_Pais, jFmt_DJ_Rg, jFmt_DJ_Telefone, jFmt_DJ_Cep, jFmt_DJ_Cnpj,
                jFmt_DJ_DataCadastro, jFmt_DJ_DataNascimento);
    }//GEN-LAST:event_jBtn_DJ_ConfirmarActionPerformed

    private void jBtn_DJ_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_CancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxt_DJ_Bairro, jTxt_DJ_Cidade, jTxt_DJ_Codigo, jTxt_DJ_Email, jTxt_DJ_Endereco, jTxt_DJ_Estado,
                jTxt_DJ_Nome, jTxt_DJ_NomeSite, jTxt_DJ_Pais, jFmt_DJ_Rg, jFmt_DJ_Telefone, jFmt_DJ_Cep, jFmt_DJ_Cnpj,
                jFmt_DJ_DataCadastro, jFmt_DJ_DataNascimento, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(true, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir);
        
        Util.limpar(jTxt_DJ_Bairro, jTxt_DJ_Cidade, jTxt_DJ_Codigo, jTxt_DJ_Email, jTxt_DJ_Endereco, jTxt_DJ_Estado,
                jTxt_DJ_Nome, jTxt_DJ_NomeSite, jTxt_DJ_Pais, jFmt_DJ_Rg, jFmt_DJ_Telefone, jFmt_DJ_Cep, jFmt_DJ_Cnpj,
                jFmt_DJ_DataCadastro, jFmt_DJ_DataNascimento);
    }//GEN-LAST:event_jBtn_DJ_CancelarActionPerformed

    private void jBtn_DJ_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_ExcluirActionPerformed
        // TODO add your handling code here:
        if(Util.perguntar("Deseja Excluir?")){
            Util.limpar(jTxt_DJ_Bairro, jTxt_DJ_Cidade, jTxt_DJ_Codigo, jTxt_DJ_Email, jTxt_DJ_Endereco, jTxt_DJ_Estado,
                jTxt_DJ_Nome, jTxt_DJ_NomeSite, jTxt_DJ_Pais, jFmt_DJ_Rg, jFmt_DJ_Telefone, jFmt_DJ_Cep, jFmt_DJ_Cnpj,
                jFmt_DJ_DataCadastro, jFmt_DJ_DataNascimento);
            Util.mensagem("Exluido com sucesso!");
        } else {
            Util.mensagem("Exclusão cancelada!");
        }
    }//GEN-LAST:event_jBtn_DJ_ExcluirActionPerformed

    private void jBtn_DJ_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_FornecedorPesquisar jDlg_DJ_FornecedorPesquisar = new JDlg_DJ_FornecedorPesquisar(null, true);
        jDlg_DJ_FornecedorPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtn_DJ_PesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_DJ_Fornecedor dialog = new JDlg_DJ_Fornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_DJ_Alterar;
    private javax.swing.JButton jBtn_DJ_Cancelar;
    private javax.swing.JButton jBtn_DJ_Confirmar;
    private javax.swing.JButton jBtn_DJ_Excluir;
    private javax.swing.JButton jBtn_DJ_Incluir;
    private javax.swing.JButton jBtn_DJ_Pesquisar;
    private javax.swing.JFormattedTextField jFmt_DJ_Cep;
    private javax.swing.JFormattedTextField jFmt_DJ_Cnpj;
    private javax.swing.JFormattedTextField jFmt_DJ_DataCadastro;
    private javax.swing.JFormattedTextField jFmt_DJ_DataNascimento;
    private javax.swing.JFormattedTextField jFmt_DJ_Rg;
    private javax.swing.JFormattedTextField jFmt_DJ_Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTxt_DJ_Bairro;
    private javax.swing.JTextField jTxt_DJ_Cidade;
    private javax.swing.JTextField jTxt_DJ_Codigo;
    private javax.swing.JTextField jTxt_DJ_Email;
    private javax.swing.JTextField jTxt_DJ_Endereco;
    private javax.swing.JTextField jTxt_DJ_Estado;
    private javax.swing.JTextField jTxt_DJ_Nome;
    private javax.swing.JTextField jTxt_DJ_NomeSite;
    private javax.swing.JTextField jTxt_DJ_Pais;
    // End of variables declaration//GEN-END:variables
}
