/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.Dj_usuarios;
import dao.DJ_UsuariosDAO;
import tools.Util;
import view_Pesquisar.JDlg_DJ_UsuariosPesquisar;
/**
 *
 * @author danie
 */
public class JDlg_DJ_Usuarios extends javax.swing.JDialog {

    private boolean incluir;
    /**
     * Creates new form JDlg_DJ_Usuarios
     */
    public JDlg_DJ_Usuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de usuários");
        setLocationRelativeTo(null);        
        Util.habilitar(false, jTxt_DJ_Codigo, jTxt_DJ_Nome, jTxt_DJ_Apelido, jFmt_DJ_Cpf, jFmt_DJ_DataDeNascimento,
                jPwf_DJ_Senha, jCbo_DJ_Nivel, jChb_DJ_Ativo, jBtn_DJ_Confirmar, jBtn_DJ_Cancelar);
    }

    
    public Dj_usuarios viewBean(){
        Dj_usuarios djUsuarios = new Dj_usuarios();
        djUsuarios.setDj_idUsuarios(Util.strToInt(jTxt_DJ_Codigo.getText()));
        djUsuarios.setDj_nome((jTxt_DJ_Nome.getText()));
        djUsuarios.setDj_apelido((jTxt_DJ_Apelido.getText()));
        djUsuarios.setDj_cpf((jFmt_DJ_Cpf.getText()));
        djUsuarios.setDj_dataNascimento(Util.strToDate(jFmt_DJ_DataDeNascimento.getText()));
        djUsuarios.setDj_senha((jPwf_DJ_Senha.getText()));
        djUsuarios.setDj_nivel((jCbo_DJ_Nivel.getSelectedIndex()));
        if(jChb_DJ_Ativo.isSelected() == true){
            djUsuarios.setDj_ativo("S");
        }else{
            djUsuarios.setDj_ativo("N");
        }
        return djUsuarios;
    }
    public void beanView(Dj_usuarios djUsuarios){
        jTxt_DJ_Codigo.setText(Util.intToStr(djUsuarios.getDj_idUsuarios()));
        jTxt_DJ_Nome.setText((djUsuarios.getDj_nome()));
        jTxt_DJ_Apelido.setText((djUsuarios.getDj_apelido()));
        jFmt_DJ_Cpf.setText((djUsuarios.getDj_cpf()));
        jFmt_DJ_DataDeNascimento.setText(Util.datetoStr(djUsuarios.getDj_dataNascimento()));
        jPwf_DJ_Senha.setText((djUsuarios.getDj_senha()));
        jCbo_DJ_Nivel.setSelectedIndex((djUsuarios.getDj_nivel()));
        jChb_DJ_Ativo.setSelected(djUsuarios.getDj_ativo().equals("S"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_DJ_Incluir = new javax.swing.JButton();
        jBtn_DJ_Alterar = new javax.swing.JButton();
        jBtn_DJ_Excluir = new javax.swing.JButton();
        jBtn_DJ_Confirmar = new javax.swing.JButton();
        jBtn_DJ_Cancelar = new javax.swing.JButton();
        jBtn_DJ_Pesquisar = new javax.swing.JButton();
        jFmt_DJ_DataDeNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPwf_DJ_Senha = new javax.swing.JPasswordField();
        jTxt_DJ_Codigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jChb_DJ_Ativo = new javax.swing.JCheckBox();
        jTxt_DJ_Nome = new javax.swing.JTextField();
        jCbo_DJ_Nivel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxt_DJ_Apelido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmt_DJ_Cpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtn_DJ_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mais-24.png"))); // NOI18N
        jBtn_DJ_Incluir.setText("Incluir");
        jBtn_DJ_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_IncluirActionPerformed(evt);
            }
        });

        jBtn_DJ_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-alter-24.png"))); // NOI18N
        jBtn_DJ_Alterar.setText("Alterar");
        jBtn_DJ_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_AlterarActionPerformed(evt);
            }
        });

        jBtn_DJ_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-entrada-proibida-24.png"))); // NOI18N
        jBtn_DJ_Excluir.setText("Excluir");
        jBtn_DJ_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_ExcluirActionPerformed(evt);
            }
        });

        jBtn_DJ_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-botão-de-opção-marcado-24.png"))); // NOI18N
        jBtn_DJ_Confirmar.setText("Confirmar");
        jBtn_DJ_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_ConfirmarActionPerformed(evt);
            }
        });

        jBtn_DJ_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancelar-24.png"))); // NOI18N
        jBtn_DJ_Cancelar.setText("Cancelar");
        jBtn_DJ_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_CancelarActionPerformed(evt);
            }
        });

        jBtn_DJ_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-24.png"))); // NOI18N
        jBtn_DJ_Pesquisar.setText("Pesquisar");
        jBtn_DJ_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_PesquisarActionPerformed(evt);
            }
        });

        try {
            jFmt_DJ_DataDeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Senha");

        jLabel1.setText("Código");

        jTxt_DJ_Codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxt_DJ_CodigoFocusLost(evt);
            }
        });

        jLabel7.setText("Nível");

        jLabel2.setText("Nome");

        jTxt_DJ_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_DJ_NomeActionPerformed(evt);
            }
        });

        jCbo_DJ_Nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "funcionario", "vendedor", "gerente" }));
        jCbo_DJ_Nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbo_DJ_NivelActionPerformed(evt);
            }
        });

        jLabel3.setText("Apelido");

        jLabel8.setText("Ativo");

        jLabel4.setText("CPF");

        try {
            jFmt_DJ_Cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Data de Nascimento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxt_DJ_Nome)
                    .addComponent(jTxt_DJ_Apelido, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxt_DJ_Codigo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFmt_DJ_Cpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFmt_DJ_DataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPwf_DJ_Senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jChb_DJ_Ativo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbo_DJ_Nivel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jBtn_DJ_Incluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Confirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Pesquisar))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(366, 366, 366)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxt_DJ_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_DJ_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxt_DJ_Apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmt_DJ_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmt_DJ_DataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPwf_DJ_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jChb_DJ_Ativo)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbo_DJ_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_DJ_Incluir)
                    .addComponent(jBtn_DJ_Alterar)
                    .addComponent(jBtn_DJ_Excluir)
                    .addComponent(jBtn_DJ_Confirmar)
                    .addComponent(jBtn_DJ_Cancelar)
                    .addComponent(jBtn_DJ_Pesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_DJ_CodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxt_DJ_CodigoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_DJ_CodigoFocusLost

    private void jTxt_DJ_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_DJ_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_DJ_NomeActionPerformed

    private void jCbo_DJ_NivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbo_DJ_NivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbo_DJ_NivelActionPerformed

    private void jBtn_DJ_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_IncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxt_DJ_Codigo, jTxt_DJ_Nome, jTxt_DJ_Apelido, jFmt_DJ_Cpf, jFmt_DJ_DataDeNascimento,
                jPwf_DJ_Senha, jCbo_DJ_Nivel, jChb_DJ_Ativo, jBtn_DJ_Confirmar, jBtn_DJ_Cancelar);
        
        Util.habilitar(false, jBtn_DJ_Alterar, jBtn_DJ_Excluir, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir);
        
        Util.limpar(jTxt_DJ_Codigo, jTxt_DJ_Nome, jTxt_DJ_Apelido, jFmt_DJ_Cpf, jFmt_DJ_DataDeNascimento,
                jPwf_DJ_Senha, jCbo_DJ_Nivel, jChb_DJ_Ativo);
        
        jTxt_DJ_Codigo.grabFocus();
        
        incluir = true;
        
    }//GEN-LAST:event_jBtn_DJ_IncluirActionPerformed

    private void jBtn_DJ_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_ConfirmarActionPerformed
        // TODO add your handling code here:
        DJ_UsuariosDAO dJ_UsuariosDAO = new DJ_UsuariosDAO();
        
        if(incluir == true){
        dJ_UsuariosDAO.insert(viewBean());
        }else{
        dJ_UsuariosDAO.update(viewBean());
        }

        Util.habilitar(false, jTxt_DJ_Codigo, jTxt_DJ_Nome, jTxt_DJ_Apelido, jFmt_DJ_Cpf, jFmt_DJ_DataDeNascimento,
                jPwf_DJ_Senha, jCbo_DJ_Nivel, jChb_DJ_Ativo, jBtn_DJ_Confirmar, jBtn_DJ_Cancelar);
        
        Util.habilitar(true, jBtn_DJ_Alterar, jBtn_DJ_Excluir, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir);
        
        Util.limpar(jTxt_DJ_Codigo, jTxt_DJ_Nome, jTxt_DJ_Apelido, jFmt_DJ_Cpf, jFmt_DJ_DataDeNascimento,
                jPwf_DJ_Senha, jCbo_DJ_Nivel, jChb_DJ_Ativo);
    }//GEN-LAST:event_jBtn_DJ_ConfirmarActionPerformed

    private void jBtn_DJ_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_CancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxt_DJ_Codigo, jTxt_DJ_Nome, jTxt_DJ_Apelido, jFmt_DJ_Cpf, jFmt_DJ_DataDeNascimento,
                jPwf_DJ_Senha, jCbo_DJ_Nivel, jChb_DJ_Ativo, jBtn_DJ_Confirmar, jBtn_DJ_Cancelar);
        
        Util.habilitar(true, jBtn_DJ_Alterar, jBtn_DJ_Excluir, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir);
        
        Util.limpar(jTxt_DJ_Codigo, jTxt_DJ_Nome, jTxt_DJ_Apelido, jFmt_DJ_Cpf, jFmt_DJ_DataDeNascimento,
                jPwf_DJ_Senha, jCbo_DJ_Nivel, jChb_DJ_Ativo);
    }//GEN-LAST:event_jBtn_DJ_CancelarActionPerformed

    private void jBtn_DJ_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_ExcluirActionPerformed
        // TODO add your handling code here:
        if(Util.perguntar("Deseja Excluir?")){
            DJ_UsuariosDAO usuariosDAO = new DJ_UsuariosDAO();
            usuariosDAO.delete(viewBean());
            Util.mensagem("Exluido com sucesso!");
        } else {
            Util.mensagem("Exclusão cancelada!");
        }
        Util.limpar(jTxt_DJ_Codigo, jTxt_DJ_Nome, jTxt_DJ_Apelido, jFmt_DJ_Cpf, jFmt_DJ_DataDeNascimento,
                jPwf_DJ_Senha, jCbo_DJ_Nivel, jChb_DJ_Ativo);
    }//GEN-LAST:event_jBtn_DJ_ExcluirActionPerformed

    private void jBtn_DJ_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_AlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxt_DJ_Nome, jTxt_DJ_Apelido, jFmt_DJ_Cpf, jFmt_DJ_DataDeNascimento,
                jPwf_DJ_Senha, jCbo_DJ_Nivel, jChb_DJ_Ativo, jBtn_DJ_Confirmar, jBtn_DJ_Cancelar);
        
        Util.habilitar(false, jBtn_DJ_Alterar, jBtn_DJ_Excluir, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jTxt_DJ_Codigo);
        
        jTxt_DJ_Nome.grabFocus();
        
        incluir = false;
        
    }//GEN-LAST:event_jBtn_DJ_AlterarActionPerformed

    private void jBtn_DJ_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_UsuariosPesquisar jDlg_DJ_UsuariosPesquisar = new JDlg_DJ_UsuariosPesquisar(null, true);
        jDlg_DJ_UsuariosPesquisar.setTelaPai(this);
        jDlg_DJ_UsuariosPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtn_DJ_PesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_DJ_Usuarios dialog = new JDlg_DJ_Usuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_DJ_Alterar;
    private javax.swing.JButton jBtn_DJ_Cancelar;
    private javax.swing.JButton jBtn_DJ_Confirmar;
    private javax.swing.JButton jBtn_DJ_Excluir;
    private javax.swing.JButton jBtn_DJ_Incluir;
    private javax.swing.JButton jBtn_DJ_Pesquisar;
    private javax.swing.JComboBox<String> jCbo_DJ_Nivel;
    private javax.swing.JCheckBox jChb_DJ_Ativo;
    private javax.swing.JFormattedTextField jFmt_DJ_Cpf;
    private javax.swing.JFormattedTextField jFmt_DJ_DataDeNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPwf_DJ_Senha;
    private javax.swing.JTextField jTxt_DJ_Apelido;
    private javax.swing.JTextField jTxt_DJ_Codigo;
    private javax.swing.JTextField jTxt_DJ_Nome;
    // End of variables declaration//GEN-END:variables
}
