/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import tools.Util;
import view_Pesquisar.JDlg_DJ_VendedorPesquisar;
import dao.DJ_VendedorDAO;
import bean.DjVendedor;

/**
 *
 * @author danie
 */
public class JDlg_DJ_Vendedor extends javax.swing.JDialog {

    private boolean incluir;
    /**
     * Creates new form JDlg_DJ_Vendedor
     */
    public JDlg_DJ_Vendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendedor");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxt_DJ_Nome, jTxt_DJ_Endereco, jTxt_DJ_Email, jTxt_DJ_Codigo,
                jFmt_DJ_CEP, jFmt_DJ_CPF, jFmt_DJ_Telefone, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
    }
    
    public DjVendedor viewBean(){
        DjVendedor djVendedor = new DjVendedor();
        djVendedor.setDjIdVendedor(Util.strToInt(jTxt_DJ_Codigo.getText()));
        djVendedor.setDjNome((jTxt_DJ_Nome.getText()));
        djVendedor.setDjEmail((jTxt_DJ_Email.getText()));
        djVendedor.setDjEndereco((jTxt_DJ_Endereco.getText()));
        djVendedor.setDjCep((jFmt_DJ_CEP.getText()));
        djVendedor.setDjCpf((jFmt_DJ_CPF.getText()));
        djVendedor.setDjTelefone((jFmt_DJ_Telefone.getText()));
        return djVendedor;
    }
    
    public void beanView(DjVendedor djVendedor){
        jTxt_DJ_Codigo.setText(Util.intToStr(djVendedor.getDjIdVendedor()));
        jTxt_DJ_Nome.setText((djVendedor.getDjNome()));
        jTxt_DJ_Email.setText((djVendedor.getDjEmail()));
        jTxt_DJ_Endereco.setText((djVendedor.getDjEndereco()));
        jFmt_DJ_CEP.setText((djVendedor.getDjCep()));
        jFmt_DJ_CPF.setText((djVendedor.getDjCpf()));
        jFmt_DJ_Telefone.setText((djVendedor.getDjTelefone()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_DJ_Cancelar = new javax.swing.JButton();
        jBtn_DJ_Pesquisar = new javax.swing.JButton();
        jBtn_DJ_Incluir = new javax.swing.JButton();
        jBtn_DJ_Alterar = new javax.swing.JButton();
        jBtn_DJ_Excluir = new javax.swing.JButton();
        jBtn_DJ_Confirmar = new javax.swing.JButton();
        jTxt_DJ_Email = new javax.swing.JTextField();
        jTxt_DJ_Codigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxt_DJ_Endereco = new javax.swing.JTextField();
        jTxt_DJ_Nome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFmt_DJ_CEP = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFmt_DJ_CPF = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmt_DJ_Telefone = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtn_DJ_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancelar-24.png"))); // NOI18N
        jBtn_DJ_Cancelar.setText("Cancelar");
        jBtn_DJ_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_CancelarActionPerformed(evt);
            }
        });

        jBtn_DJ_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-24.png"))); // NOI18N
        jBtn_DJ_Pesquisar.setText("Pesquisar");
        jBtn_DJ_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_PesquisarActionPerformed(evt);
            }
        });

        jBtn_DJ_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mais-24.png"))); // NOI18N
        jBtn_DJ_Incluir.setText("Incluir");
        jBtn_DJ_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_IncluirActionPerformed(evt);
            }
        });

        jBtn_DJ_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-alter-24.png"))); // NOI18N
        jBtn_DJ_Alterar.setText("Alterar");
        jBtn_DJ_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_AlterarActionPerformed(evt);
            }
        });

        jBtn_DJ_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-entrada-proibida-24.png"))); // NOI18N
        jBtn_DJ_Excluir.setText("Excluir");
        jBtn_DJ_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_ExcluirActionPerformed(evt);
            }
        });

        jBtn_DJ_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-botão-de-opção-marcado-24.png"))); // NOI18N
        jBtn_DJ_Confirmar.setText("Confirmar");
        jBtn_DJ_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DJ_ConfirmarActionPerformed(evt);
            }
        });

        jLabel6.setText("Endereço");

        jLabel2.setText("Nome");

        jLabel7.setText("CEP");

        try {
            jFmt_DJ_CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("CPF");

        try {
            jFmt_DJ_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmt_DJ_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmt_DJ_CPFActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefone");

        try {
            jFmt_DJ_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("E-mail");

        jLabel1.setText("Código");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxt_DJ_Codigo)
                    .addComponent(jTxt_DJ_Nome)
                    .addComponent(jTxt_DJ_Endereco)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmt_DJ_Telefone)
                            .addComponent(jFmt_DJ_CPF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmt_DJ_CEP)
                            .addComponent(jTxt_DJ_Email)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn_DJ_Incluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Confirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_DJ_Pesquisar))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(280, 280, 280)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(271, 271, 271)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_DJ_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_DJ_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jFmt_DJ_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmt_DJ_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmt_DJ_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_DJ_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTxt_DJ_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_DJ_Incluir)
                    .addComponent(jBtn_DJ_Alterar)
                    .addComponent(jBtn_DJ_Excluir)
                    .addComponent(jBtn_DJ_Confirmar)
                    .addComponent(jBtn_DJ_Cancelar)
                    .addComponent(jBtn_DJ_Pesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFmt_DJ_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmt_DJ_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmt_DJ_CPFActionPerformed

    private void jBtn_DJ_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_IncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxt_DJ_Nome, jTxt_DJ_Endereco, jTxt_DJ_Email, jTxt_DJ_Codigo,
                jFmt_DJ_CEP, jFmt_DJ_CPF, jFmt_DJ_Telefone, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(false, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir);
        
        Util.limpar(jTxt_DJ_Nome, jTxt_DJ_Endereco, jTxt_DJ_Email, jTxt_DJ_Codigo,
                jFmt_DJ_CEP, jFmt_DJ_CPF, jFmt_DJ_Telefone);
        
        jTxt_DJ_Codigo.grabFocus();
        
        incluir = true;
    }//GEN-LAST:event_jBtn_DJ_IncluirActionPerformed

    private void jBtn_DJ_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_AlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxt_DJ_Nome, jTxt_DJ_Endereco, jTxt_DJ_Email,
                jFmt_DJ_CEP, jFmt_DJ_CPF, jFmt_DJ_Telefone, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(false, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir, jTxt_DJ_Codigo);
        
        jTxt_DJ_Nome.grabFocus();
        
        incluir = false;
    }//GEN-LAST:event_jBtn_DJ_AlterarActionPerformed

    private void jBtn_DJ_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_CancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxt_DJ_Nome, jTxt_DJ_Endereco, jTxt_DJ_Email, jTxt_DJ_Codigo,
                jFmt_DJ_CEP, jFmt_DJ_CPF, jFmt_DJ_Telefone, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(true, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir);
        
        Util.limpar(jTxt_DJ_Nome, jTxt_DJ_Endereco, jTxt_DJ_Email, jTxt_DJ_Codigo,
                jFmt_DJ_CEP, jFmt_DJ_CPF, jFmt_DJ_Telefone);
    }//GEN-LAST:event_jBtn_DJ_CancelarActionPerformed

    private void jBtn_DJ_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_ConfirmarActionPerformed
        // TODO add your handling code here:
        DJ_VendedorDAO dJ_VendedorDAO = new DJ_VendedorDAO();
        
        if(incluir == true){
            dJ_VendedorDAO.insert(viewBean());
        }else{
            dJ_VendedorDAO.update(viewBean());
        }
        
        Util.habilitar(false, jTxt_DJ_Nome, jTxt_DJ_Endereco, jTxt_DJ_Email, jTxt_DJ_Codigo,
                jFmt_DJ_CEP, jFmt_DJ_CPF, jFmt_DJ_Telefone, jBtn_DJ_Cancelar, jBtn_DJ_Confirmar);
        
        Util.habilitar(true, jBtn_DJ_Alterar, jBtn_DJ_Pesquisar, jBtn_DJ_Incluir, jBtn_DJ_Excluir);
        
        Util.limpar(jTxt_DJ_Nome, jTxt_DJ_Endereco, jTxt_DJ_Email, jTxt_DJ_Codigo,
                jFmt_DJ_CEP, jFmt_DJ_CPF, jFmt_DJ_Telefone);
    }//GEN-LAST:event_jBtn_DJ_ConfirmarActionPerformed

    private void jBtn_DJ_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_ExcluirActionPerformed
        // TODO add your handling code here:
        if(Util.perguntar("Deseja Excluir?")){
            DJ_VendedorDAO dJ_VendedorDAO = new DJ_VendedorDAO();
            dJ_VendedorDAO.delete(viewBean());
            Util.mensagem("Exluido com sucesso!");
        } else {
            Util.mensagem("Exclusão cancelada!");
        }
            Util.limpar(jTxt_DJ_Nome, jTxt_DJ_Endereco, jTxt_DJ_Email, jTxt_DJ_Codigo,
                jFmt_DJ_CEP, jFmt_DJ_CPF, jFmt_DJ_Telefone);
    }//GEN-LAST:event_jBtn_DJ_ExcluirActionPerformed

    private void jBtn_DJ_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DJ_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_VendedorPesquisar jDlg_DJ_VendedorPesquisar = new JDlg_DJ_VendedorPesquisar(null, true);
        jDlg_DJ_VendedorPesquisar.SetTelaPai(this);
        jDlg_DJ_VendedorPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtn_DJ_PesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_DJ_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_DJ_Vendedor dialog = new JDlg_DJ_Vendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_DJ_Alterar;
    private javax.swing.JButton jBtn_DJ_Cancelar;
    private javax.swing.JButton jBtn_DJ_Confirmar;
    private javax.swing.JButton jBtn_DJ_Excluir;
    private javax.swing.JButton jBtn_DJ_Incluir;
    private javax.swing.JButton jBtn_DJ_Pesquisar;
    private javax.swing.JFormattedTextField jFmt_DJ_CEP;
    private javax.swing.JFormattedTextField jFmt_DJ_CPF;
    private javax.swing.JFormattedTextField jFmt_DJ_Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTxt_DJ_Codigo;
    private javax.swing.JTextField jTxt_DJ_Email;
    private javax.swing.JTextField jTxt_DJ_Endereco;
    private javax.swing.JTextField jTxt_DJ_Nome;
    // End of variables declaration//GEN-END:variables
}
