/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author danie
 */
public class JFrm_DJ_Principal extends javax.swing.JFrame {

    /**
     * Creates new form JFrm_DJ_Principal
     */
    public JFrm_DJ_Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Sistema de compras de flores artificiais");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnu_DJ_Cadastros = new javax.swing.JMenu();
        jMni_DJ_Usuarios = new javax.swing.JMenuItem();
        jMni_DJ_Fornecedor = new javax.swing.JMenuItem();
        jMni_DJ_Vendedor = new javax.swing.JMenuItem();
        jMni_DJ_Produtos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMni_DJ_Sair = new javax.swing.JMenuItem();
        jMnu_DJ_Movimentos = new javax.swing.JMenu();
        jMni_DJ_Compras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnu_DJ_Cadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cadastro-24.png"))); // NOI18N
        jMnu_DJ_Cadastros.setText("Cadastros");

        jMni_DJ_Usuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_DJ_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuário-24.png"))); // NOI18N
        jMni_DJ_Usuarios.setText("Usuários");
        jMni_DJ_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_DJ_UsuariosActionPerformed(evt);
            }
        });
        jMnu_DJ_Cadastros.add(jMni_DJ_Usuarios);

        jMni_DJ_Fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_DJ_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-fornecedor-24.png"))); // NOI18N
        jMni_DJ_Fornecedor.setText("Fornecedor");
        jMni_DJ_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_DJ_FornecedorActionPerformed(evt);
            }
        });
        jMnu_DJ_Cadastros.add(jMni_DJ_Fornecedor);

        jMni_DJ_Vendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_DJ_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pessoa-24.png"))); // NOI18N
        jMni_DJ_Vendedor.setText("Vendedor");
        jMni_DJ_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_DJ_VendedorActionPerformed(evt);
            }
        });
        jMnu_DJ_Cadastros.add(jMni_DJ_Vendedor);

        jMni_DJ_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_DJ_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-flores-24.png"))); // NOI18N
        jMni_DJ_Produtos.setText("Produtos");
        jMni_DJ_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_DJ_ProdutosActionPerformed(evt);
            }
        });
        jMnu_DJ_Cadastros.add(jMni_DJ_Produtos);
        jMnu_DJ_Cadastros.add(jSeparator1);

        jMni_DJ_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMni_DJ_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-exportar-24.png"))); // NOI18N
        jMni_DJ_Sair.setText("Sair");
        jMni_DJ_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_DJ_SairActionPerformed(evt);
            }
        });
        jMnu_DJ_Cadastros.add(jMni_DJ_Sair);

        jMenuBar1.add(jMnu_DJ_Cadastros);

        jMnu_DJ_Movimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-movimento-24.png"))); // NOI18N
        jMnu_DJ_Movimentos.setText("Movimentos");

        jMni_DJ_Compras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_DJ_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-carrinho-de-compras-24.png"))); // NOI18N
        jMni_DJ_Compras.setText("Compras");
        jMnu_DJ_Movimentos.add(jMni_DJ_Compras);

        jMenuBar1.add(jMnu_DJ_Movimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMni_DJ_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_DJ_UsuariosActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_Usuarios jDlg_DJ_Usuarios = new JDlg_DJ_Usuarios(null, true);
        jDlg_DJ_Usuarios.setVisible(true);
    }//GEN-LAST:event_jMni_DJ_UsuariosActionPerformed

    private void jMni_DJ_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_DJ_VendedorActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_Clientes jDlg_DJ_Vendedor = new JDlg_DJ_Clientes(null, true);
        jDlg_DJ_Vendedor.setVisible(true);
    }//GEN-LAST:event_jMni_DJ_VendedorActionPerformed

    private void jMni_DJ_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_DJ_FornecedorActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_Clientes jDlg_DJ_Vendedor = new JDlg_DJ_Clientes(null, true);
        jDlg_DJ_Vendedor.setVisible(true);
    }//GEN-LAST:event_jMni_DJ_FornecedorActionPerformed

    private void jMni_DJ_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_DJ_ProdutosActionPerformed
        // TODO add your handling code here:
        JDlg_DJ_Produtos jDlg_DJ_Produtos = new JDlg_DJ_Produtos(null, true);
        jDlg_DJ_Produtos.setVisible(true);
    }//GEN-LAST:event_jMni_DJ_ProdutosActionPerformed

    private void jMni_DJ_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_DJ_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMni_DJ_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrm_DJ_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrm_DJ_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrm_DJ_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrm_DJ_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrm_DJ_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMni_DJ_Compras;
    private javax.swing.JMenuItem jMni_DJ_Fornecedor;
    private javax.swing.JMenuItem jMni_DJ_Produtos;
    private javax.swing.JMenuItem jMni_DJ_Sair;
    private javax.swing.JMenuItem jMni_DJ_Usuarios;
    private javax.swing.JMenuItem jMni_DJ_Vendedor;
    private javax.swing.JMenu jMnu_DJ_Cadastros;
    private javax.swing.JMenu jMnu_DJ_Movimentos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
