package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * dj_clientes generated by hbm2java
 */
@Entity
@Table(name="dj_clientes"
    ,catalog="db_daniel_jin"
)
public class dj_clientes  implements java.io.Serializable {


     private int djIdVendedor;
     private String djNome;
     private String djCpf;
     private String djTelefone;
     private String djEmail;
     private String djEndereco;
     private String djCep;

    public dj_clientes() {
    }

	
    public dj_clientes(int djIdVendedor, String djNome, String djCpf, String djEmail, String djEndereco, String djCep) {
        this.djIdVendedor = djIdVendedor;
        this.djNome = djNome;
        this.djCpf = djCpf;
        this.djEmail = djEmail;
        this.djEndereco = djEndereco;
        this.djCep = djCep;
    }
    public dj_clientes(int djIdVendedor, String djNome, String djCpf, String djTelefone, String djEmail, String djEndereco, String djCep) {
       this.djIdVendedor = djIdVendedor;
       this.djNome = djNome;
       this.djCpf = djCpf;
       this.djTelefone = djTelefone;
       this.djEmail = djEmail;
       this.djEndereco = djEndereco;
       this.djCep = djCep;
    }
   
     @Id 

    
    @Column(name="dj_idVendedor", unique=true, nullable=false)
    public int getDjIdVendedor() {
        return this.djIdVendedor;
    }
    
    public void setDjIdVendedor(int djIdVendedor) {
        this.djIdVendedor = djIdVendedor;
    }

    
    @Column(name="dj_nome", nullable=false, length=50)
    public String getDjNome() {
        return this.djNome;
    }
    
    public void setDjNome(String djNome) {
        this.djNome = djNome;
    }

    
    @Column(name="dj_cpf", nullable=false, length=14)
    public String getDjCpf() {
        return this.djCpf;
    }
    
    public void setDjCpf(String djCpf) {
        this.djCpf = djCpf;
    }

    
    @Column(name="dj_telefone", length=14)
    public String getDjTelefone() {
        return this.djTelefone;
    }
    
    public void setDjTelefone(String djTelefone) {
        this.djTelefone = djTelefone;
    }

    
    @Column(name="dj_email", nullable=false, length=80)
    public String getDjEmail() {
        return this.djEmail;
    }
    
    public void setDjEmail(String djEmail) {
        this.djEmail = djEmail;
    }

    
    @Column(name="dj_endereco", nullable=false, length=50)
    public String getDjEndereco() {
        return this.djEndereco;
    }
    
    public void setDjEndereco(String djEndereco) {
        this.djEndereco = djEndereco;
    }

    
    @Column(name="dj_cep", nullable=false, length=9)
    public String getDjCep() {
        return this.djCep;
    }
    
    public void setDjCep(String djCep) {
        this.djCep = djCep;
    }




}


