package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * dj_compras_produtos generated by hbm2java
 */
@Entity
@Table(name="dj_compras_produtos"
    ,catalog="db_daniel_jin"
)
public class dj_compras_produtos  implements java.io.Serializable {


     private int dj_id_compras_produtos;
     private dj_compras dj_fkCompras;
     private dj_produtos dj_fkProdutos;
     private int dj_quantidade;
     private double dj_valor_unitario;

    public dj_compras_produtos() {
    }

    public dj_compras_produtos(int djIdComprasProdutos, dj_compras dj_Compras, dj_produtos dj_Produtos, int dj_quantidade, double dj_valor_unitario) {
       this.dj_id_compras_produtos = djIdComprasProdutos;
       this.dj_fkCompras = dj_Compras;
       this.dj_fkProdutos = dj_Produtos;
       this.dj_quantidade = dj_quantidade;
       this.dj_valor_unitario = dj_valor_unitario;
    }
   
     @Id 

    
    @Column(name="dj_id_compras_produtos", unique=true, nullable=false)
    public int getDj_id_compras_produtos() {
        return this.dj_id_compras_produtos;
    }
    
    public void setDj_id_compras_produtos(int dj_id_compras_produtos) {
        this.dj_id_compras_produtos = dj_id_compras_produtos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dj_fkCompras", nullable=false)
    public dj_compras getDj_fkCompras() {
        return this.dj_fkCompras;
    }
    
    public void setDj_fkCompras(dj_compras dj_fkCompras) {
        this.dj_fkCompras = dj_fkCompras;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dj_fkProdutos", nullable=false)
    public dj_produtos getDj_fkProdutos() {
        return this.dj_fkProdutos;
    }
    
    public void setDj_fkProdutos(dj_produtos dj_fkProdutos) {
        this.dj_fkProdutos = dj_fkProdutos;
    }

    
    @Column(name="dj_quantidade", nullable=false)
    public int getDj_quantidade() {
        return this.dj_quantidade;
    }
    
    public void setDj_quantidade(int dj_quantidade) {
        this.dj_quantidade = dj_quantidade;
    }

    
    @Column(name="dj_valor_unitario", nullable=false, precision=10)
    public double getDj_valor_unitario() {
        return this.dj_valor_unitario;
    }
    
    public void setDj_valor_unitario(double dj_valor_unitario) {
        this.dj_valor_unitario = dj_valor_unitario;
    }




}


