package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * dj_compras_produtos generated by hbm2java
 */
@Entity
@Table(name="dj_compras_produtos"
    ,catalog="db_daniel_jin"
)
public class dj_compras_produtos  implements java.io.Serializable {


     private int djIdComprasProdutos;
     private dj_compras djCompras;
     private dj_produtos djProdutos;
     private int djQuantidade;
     private double djValorUnitario;

    public dj_compras_produtos() {
    }

    public dj_compras_produtos(int djIdComprasProdutos, dj_compras djCompras, dj_produtos djProdutos, int djQuantidade, double djValorUnitario) {
       this.djIdComprasProdutos = djIdComprasProdutos;
       this.djCompras = djCompras;
       this.djProdutos = djProdutos;
       this.djQuantidade = djQuantidade;
       this.djValorUnitario = djValorUnitario;
    }
   
     @Id 

    
    @Column(name="dj_id_compras_produtos", unique=true, nullable=false)
    public int getDjIdComprasProdutos() {
        return this.djIdComprasProdutos;
    }
    
    public void setDjIdComprasProdutos(int djIdComprasProdutos) {
        this.djIdComprasProdutos = djIdComprasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dj_fkCompras", nullable=false)
    public dj_compras getDjCompras() {
        return this.djCompras;
    }
    
    public void setDjCompras(dj_compras djCompras) {
        this.djCompras = djCompras;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dj_fkProdutos", nullable=false)
    public dj_produtos getDjProdutos() {
        return this.djProdutos;
    }
    
    public void setDjProdutos(dj_produtos djProdutos) {
        this.djProdutos = djProdutos;
    }

    
    @Column(name="dj_quantidade", nullable=false)
    public int getDjQuantidade() {
        return this.djQuantidade;
    }
    
    public void setDjQuantidade(int djQuantidade) {
        this.djQuantidade = djQuantidade;
    }

    
    @Column(name="dj_valor_unitario", nullable=false, precision=10)
    public double getDjValorUnitario() {
        return this.djValorUnitario;
    }
    
    public void setDjValorUnitario(double djValorUnitario) {
        this.djValorUnitario = djValorUnitario;
    }




}


