package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * dj_compras generated by hbm2java
 */
@Entity
@Table(name="dj_compras"
    ,catalog="db_daniel_jin"
)
public class dj_compras  implements java.io.Serializable {


     private int dj_idCompras;
     private dj_fornecedor dj_fkFornecedor;
     private dj_usuarios dj_fkUsuarios;
     private Date dj_dataCompras;
     private double dj_total;

    public dj_compras() {
    }

	
    public dj_compras(int dj_idCompras, Date dj_dataCompras, double dj_total) {
        this.dj_idCompras = dj_idCompras;
        this.dj_dataCompras = dj_dataCompras;
        this.dj_total = dj_total;
    }
    public dj_compras(int dj_idCompras, dj_fornecedor dj_Fornecedor, dj_usuarios dj_Usuarios, Date dj_dataCompras, double dj_total) {
       this.dj_idCompras = dj_idCompras;
       this.dj_fkFornecedor = dj_Fornecedor;
       this.dj_fkUsuarios = dj_Usuarios;
       this.dj_dataCompras = dj_dataCompras;
       this.dj_total = dj_total;
    }
   
     @Id 

    
    @Column(name="dj_idCompras", unique=true, nullable=false)
    public int getDj_idCompras() {
        return this.dj_idCompras;
    }
    
    public void setDj_idCompras(int dj_idCompras) {
        this.dj_idCompras = dj_idCompras;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dj_fkFornecedor")
    public dj_fornecedor getDj_fkFornecedor() {
        return this.dj_fkFornecedor;
    }
    
    public void setDj_fkFornecedor(dj_fornecedor dj_fkFornecedor) {
        this.dj_fkFornecedor = dj_fkFornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dj_fkUsuario")
    public dj_usuarios getDj_fkUsuarios() {
        return this.dj_fkUsuarios;
    }
    
    public void setDj_fkUsuarios(dj_usuarios dj_fkUsuarios) {
        this.dj_fkUsuarios = dj_fkUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dj_dataCompras", nullable=false, length=10)
    public Date getDj_dataCompras() {
        return this.dj_dataCompras;
    }
    
    public void setDj_dataCompras(Date dj_dataCompras) {
        this.dj_dataCompras = dj_dataCompras;
    }

    
    @Column(name="dj_total", nullable=false, precision=10)
    public double getDj_total() {
        return this.dj_total;
    }
    
    public void setDj_total(double dj_total) {
        this.dj_total = dj_total;
    }


}


