package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dj_clientes generated by hbm2java
 */
@Entity
@Table(name="Dj_clientes"
    ,catalog="db_daniel_jin"
)
public class Dj_clientes  implements java.io.Serializable {


     private int dj_idClientes;
     private String dj_nome;
     private String dj_cpf;
     private String dj_telefone;
     private String dj_email;
     private String dj_endereco;
     private String dj_cep;

    public Dj_clientes() {
    }

	
    public Dj_clientes(int dj_idClientes, String dj_nome, String dj_cpf, String dj_email, String dj_endereco, String dj_cep) {
        this.dj_idClientes = dj_idClientes;
        this.dj_nome = dj_nome;
        this.dj_cpf = dj_cpf;
        this.dj_email = dj_email;
        this.dj_endereco = dj_endereco;
        this.dj_cep = dj_cep;
    }
    public Dj_clientes(int dj_idClientes, String dj_nome, String dj_cpf, String dj_telefone, String dj_email, String dj_endereco, String dj_cep) {
       this.dj_idClientes = dj_idClientes;
       this.dj_nome = dj_nome;
       this.dj_cpf = dj_cpf;
       this.dj_telefone = dj_telefone;
       this.dj_email = dj_email;
       this.dj_endereco = dj_endereco;
       this.dj_cep = dj_cep;
    }
   
     @Id 

    
    @Column(name="dj_idClientes", unique=true, nullable=false)
    public int getDj_idClientes() {
        return this.dj_idClientes;
    }
    
    public void setDj_idClientes(int dj_idClientes) {
        this.dj_idClientes = dj_idClientes;
    }

    
    @Column(name="dj_nome", nullable=false, length=50)
    public String getDj_nome() {
        return this.dj_nome;
    }
    
    public void setDj_nome(String dj_nome) {
        this.dj_nome = dj_nome;
    }

    
    @Column(name="dj_cpf", nullable=false, length=14)
    public String getDj_cpf() {
        return this.dj_cpf;
    }
    
    public void setDj_cpf(String dj_cpf) {
        this.dj_cpf = dj_cpf;
    }

    
    @Column(name="dj_telefone", length=14)
    public String getDj_telefone() {
        return this.dj_telefone;
    }
    
    public void setDj_telefone(String dj_telefone) {
        this.dj_telefone = dj_telefone;
    }

    
    @Column(name="dj_email", nullable=false, length=80)
    public String getDj_email() {
        return this.dj_email;
    }
    
    public void setDj_email(String dj_email) {
        this.dj_email = dj_email;
    }

    
    @Column(name="dj_endereco", nullable=false, length=50)
    public String getDj_endereco() {
        return this.dj_endereco;
    }
    
    public void setDj_endereco(String dj_endereco) {
        this.dj_endereco = dj_endereco;
    }

    
    @Column(name="dj_cep", nullable=false, length=9)
    public String getDj_cep() {
        return this.dj_cep;
    }
    
    public void setDj_cep(String dj_cep) {
        this.dj_cep = dj_cep;
    }




}


