package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * dj_produtos generated by hbm2java
 */
@Entity
@Table(name="dj_produtos"
    ,catalog="db_daniel_jin"
)
public class dj_produtos  implements java.io.Serializable {


     private int dj_idProdutos;
     private String dj_nome;
     private double dj_preco;
     private String dj_descricao;
     private double dj_avaliacao;
     private String dj_nome_da_flor;
     private String dj_material;

    public dj_produtos() {
    }

	
    public dj_produtos(int dj_idProdutos, String dj_nome, double dj_preco, String dj_descricao, double dj_avaliacao, String dj_nome_da_flor, String djMaterial) {
        this.dj_idProdutos = dj_idProdutos;
        this.dj_nome = dj_nome;
        this.dj_preco = dj_preco;
        this.dj_descricao = dj_descricao;
        this.dj_avaliacao = dj_avaliacao;
        this.dj_nome_da_flor = dj_nome_da_flor;
        this.dj_material = djMaterial;
    }
   
     @Id 

    
    @Column(name="dj_idProdutos", unique=true, nullable=false)
    public int getDj_idProdutos() {
        return this.dj_idProdutos;
    }
    
    public void setDj_idProdutos(int dj_idProdutos) {
        this.dj_idProdutos = dj_idProdutos;
    }

    
    @Column(name="dj_nome", nullable=false, length=50)
    public String getDj_nome() {
        return this.dj_nome;
    }
    
    public void setDj_nome(String dj_nome) {
        this.dj_nome = dj_nome;
    }

    
    @Column(name="dj_preco", nullable=false, precision=10)
    public double getDj_preco() {
        return this.dj_preco;
    }
    
    public void setDj_preco(double dj_preco) {
        this.dj_preco = dj_preco;
    }

    
    @Column(name="dj_descricao", nullable=false)
    public String getDj_descricao() {
        return this.dj_descricao;
    }
    
    public void setDj_descricao(String dj_descricao) {
        this.dj_descricao = dj_descricao;
    }

    
    @Column(name="dj_avaliacao", nullable=false, length=45)
    public double getDj_avaliacao() {
        return this.dj_avaliacao;
    }
    
    public void setDj_avaliacao(double dj_avaliacao) {
        this.dj_avaliacao = dj_avaliacao;
    }

    
    @Column(name="dj_nome_da_flor", nullable=false, length=45)
    public String getDj_nome_da_flor() {
        return this.dj_nome_da_flor;
    }
    
    public void setDj_nome_da_flor(String dj_nome_da_flor) {
        this.dj_nome_da_flor = dj_nome_da_flor;
    }

    
    @Column(name="dj_material", nullable=false, length=45)
    public String getDj_material() {
        return this.dj_material;
    }
    
    public void setDj_material(String dj_material) {
        this.dj_material = dj_material;
    }



}


