package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DjUsuarios generated by hbm2java
 */
@Entity
@Table(name="dj_usuarios"
    ,catalog="db_daniel_jin"
)
public class Dj_usuarios  implements java.io.Serializable {


     private int dj_idUsuarios;
     private String dj_nome;
     private String dj_apelido;
     private String dj_cpf;
     private Date dj_dataNascimento;
     private String dj_senha;
     private int dj_nivel;
     private String dj_ativo;

    public Dj_usuarios() {
    }

	
    public Dj_usuarios(int dj_idUsuarios, String dj_nome, String dj_apelido, String dj_cpf, String dj_senha, int dj_nivel, String dj_ativo) {
        this.dj_idUsuarios = dj_idUsuarios;
        this.dj_nome = dj_nome;
        this.dj_apelido = dj_apelido;
        this.dj_cpf = dj_cpf;
        this.dj_senha = dj_senha;
        this.dj_nivel = dj_nivel;
        this.dj_ativo = dj_ativo;
    }
    public Dj_usuarios(int dj_idUsuarios, String dj_nome, String dj_apelido, String dj_cpf, Date dj_dataNascimento, String dj_senha, int dj_nivel, String dj_ativo) {
       this.dj_idUsuarios = dj_idUsuarios;
       this.dj_nome = dj_nome;
       this.dj_apelido = dj_apelido;
       this.dj_cpf = dj_cpf;
       this.dj_dataNascimento = dj_dataNascimento;
       this.dj_senha = dj_senha;
       this.dj_nivel = dj_nivel;
       this.dj_ativo = dj_ativo;

    }
   
     @Id 

    
    @Column(name="dj_idUsuarios", unique=true, nullable=false)
    public int getDj_idUsuarios() {
        return this.dj_idUsuarios;
    }
    
    public void setDj_idUsuarios(int dj_idUsuarios) {
        this.dj_idUsuarios = dj_idUsuarios;
    }

    
    @Column(name="dj_nome", nullable=false, length=50)
    public String getDj_nome() {
        return this.dj_nome;
    }
    
    public void setDj_nome(String dj_nome) {
        this.dj_nome = dj_nome;
    }

    
    @Column(name="dj_apelido", nullable=false, length=25)
    public String getDj_apelido() {
        return this.dj_apelido;
    }
    
    public void setDj_apelido(String dj_apelido) {
        this.dj_apelido = dj_apelido;
    }

    
    @Column(name="dj_cpf", nullable=false, length=14)
    public String getDj_cpf() {
        return this.dj_cpf;
    }
    
    public void setDj_cpf(String dj_cpf) {
        this.dj_cpf = dj_cpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dj_dataNascimento", length=10)
    public Date getDj_dataNascimento() {
        return this.dj_dataNascimento;
    }
    
    public void setDj_dataNascimento(Date dj_dataNascimento) {
        this.dj_dataNascimento = dj_dataNascimento;
    }

    
    @Column(name="dj_senha", nullable=false, length=20)
    public String getDj_senha() {
        return this.dj_senha;
    }
    
    public void setDj_senha(String dj_senha) {
        this.dj_senha = dj_senha;
    }

    
    @Column(name="dj_nivel", nullable=false)
    public int getDj_nivel() {
        return this.dj_nivel;
    }
    
    public void setDj_nivel(int dj_nivel) {
        this.dj_nivel = dj_nivel;
    }

    
    @Column(name="dj_ativo", nullable=false, length=1)
    public String getDj_ativo() {
        return this.dj_ativo;
    }
    
    public void setDj_ativo(String dj_ativo) {
        this.dj_ativo = dj_ativo;
    }

    public void getDjIdUsuarios(int strToInt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


     @Override
    public String toString(){
        return this.getDj_nome();
    }
    
    @Override
    public boolean equals(Object object){
        if (object instanceof Dj_usuarios){
            Dj_usuarios dj_usuarios = (Dj_usuarios)object;
            if (this.getDj_idUsuarios()== dj_usuarios.getDj_idUsuarios()){
                return true;
            }
        }
         return false;
    }
}


