package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DjCompras generated by hbm2java
 */
@Entity
@Table(name="dj_compras"
    ,catalog="dj_sistemadevendasperfume_daniel"
)
public class DjCompras  implements java.io.Serializable {


     private int djIdCompras;
     private DjFornecedor djFornecedor;
     private DjUsuarios djUsuarios;
     private Date djDataCompras;
     private double djTotal;

    public DjCompras() {
    }

	
    public DjCompras(int djIdCompras, Date djDataCompras, double djTotal) {
        this.djIdCompras = djIdCompras;
        this.djDataCompras = djDataCompras;
        this.djTotal = djTotal;
    }
    public DjCompras(int djIdCompras, DjFornecedor djFornecedor, DjUsuarios djUsuarios, Date djDataCompras, double djTotal) {
       this.djIdCompras = djIdCompras;
       this.djFornecedor = djFornecedor;
       this.djUsuarios = djUsuarios;
       this.djDataCompras = djDataCompras;
       this.djTotal = djTotal;
    }
   
     @Id 

    
    @Column(name="dj_idCompras", unique=true, nullable=false)
    public int getDjIdCompras() {
        return this.djIdCompras;
    }
    
    public void setDjIdCompras(int djIdCompras) {
        this.djIdCompras = djIdCompras;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dj_fkFornecedor")
    public DjFornecedor getDjFornecedor() {
        return this.djFornecedor;
    }
    
    public void setDjFornecedor(DjFornecedor djFornecedor) {
        this.djFornecedor = djFornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dj_fkUsuario")
    public DjUsuarios getDjUsuarios() {
        return this.djUsuarios;
    }
    
    public void setDjUsuarios(DjUsuarios djUsuarios) {
        this.djUsuarios = djUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dj_dataCompras", nullable=false, length=10)
    public Date getDjDataCompras() {
        return this.djDataCompras;
    }
    
    public void setDjDataCompras(Date djDataCompras) {
        this.djDataCompras = djDataCompras;
    }

    
    @Column(name="dj_total", nullable=false, precision=10)
    public double getDjTotal() {
        return this.djTotal;
    }
    
    public void setDjTotal(double djTotal) {
        this.djTotal = djTotal;
    }


}


