package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DjComprasProdutos generated by hbm2java
 */
@Entity
@Table(name="dj_compras_produtos"
    ,catalog="dj_sistemadevendasperfume_daniel"
)
public class DjComprasProdutos  implements java.io.Serializable {


     private int djIdComprasProdutos;
     private DjCompras djCompras;
     private DjProdutos djProdutos;
     private int djQuantidade;
     private BigDecimal djValorUnitario;

    public DjComprasProdutos() {
    }

    public DjComprasProdutos(int djIdComprasProdutos, DjCompras djCompras, DjProdutos djProdutos, int djQuantidade, BigDecimal djValorUnitario) {
       this.djIdComprasProdutos = djIdComprasProdutos;
       this.djCompras = djCompras;
       this.djProdutos = djProdutos;
       this.djQuantidade = djQuantidade;
       this.djValorUnitario = djValorUnitario;
    }
   
     @Id 

    
    @Column(name="dj_id_compras_produtos", unique=true, nullable=false)
    public int getDjIdComprasProdutos() {
        return this.djIdComprasProdutos;
    }
    
    public void setDjIdComprasProdutos(int djIdComprasProdutos) {
        this.djIdComprasProdutos = djIdComprasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dj_fkCompras", nullable=false)
    public DjCompras getDjCompras() {
        return this.djCompras;
    }
    
    public void setDjCompras(DjCompras djCompras) {
        this.djCompras = djCompras;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dj_fkProdutos", nullable=false)
    public DjProdutos getDjProdutos() {
        return this.djProdutos;
    }
    
    public void setDjProdutos(DjProdutos djProdutos) {
        this.djProdutos = djProdutos;
    }

    
    @Column(name="dj_quantidade", nullable=false)
    public int getDjQuantidade() {
        return this.djQuantidade;
    }
    
    public void setDjQuantidade(int djQuantidade) {
        this.djQuantidade = djQuantidade;
    }

    
    @Column(name="dj_valor_unitario", nullable=false, precision=10)
    public BigDecimal getDjValorUnitario() {
        return this.djValorUnitario;
    }
    
    public void setDjValorUnitario(BigDecimal djValorUnitario) {
        this.djValorUnitario = djValorUnitario;
    }




}


