package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DjFornecedor generated by hbm2java
 */
@Entity
@Table(name="dj_fornecedor"
    ,catalog="dj_sistemadevendasperfume_daniel"
)
public class DjFornecedor  implements java.io.Serializable {


     private int djIdFornecedor;
     private String djNome;
     private String djCnpj;
     private String djRg;
     private Date djDataNascimento;
     private String djEmail;
     private String djTelefone;
     private String djEndereco;
     private String djCidade;
     private String djBairro;
     private String djCep;
     private String djPais;
     private String djEstado;
     private String djNomeSite;
     private Date djDataCadastro;


    public DjFornecedor() {
    }

	
    public DjFornecedor(int djIdFornecedor, String djNome, String djCnpj, String djRg, String djEmail, String djEndereco, String djCidade, String djBairro, String djCep, String djPais, String djEstado) {
        this.djIdFornecedor = djIdFornecedor;
        this.djNome = djNome;
        this.djCnpj = djCnpj;
        this.djRg = djRg;
        this.djEmail = djEmail;
        this.djEndereco = djEndereco;
        this.djCidade = djCidade;
        this.djBairro = djBairro;
        this.djCep = djCep;
        this.djPais = djPais;
        this.djEstado = djEstado;
    }
    public DjFornecedor(int djIdFornecedor, String djNome, String djCnpj, String djRg, Date djDataNascimento, String djEmail, String djTelefone, String djEndereco, String djCidade, String djBairro, String djCep, String djPais, String djEstado, String djNomeSite, Date djDataCadastro) {
       this.djIdFornecedor = djIdFornecedor;
       this.djNome = djNome;
       this.djCnpj = djCnpj;
       this.djRg = djRg;
       this.djDataNascimento = djDataNascimento;
       this.djEmail = djEmail;
       this.djTelefone = djTelefone;
       this.djEndereco = djEndereco;
       this.djCidade = djCidade;
       this.djBairro = djBairro;
       this.djCep = djCep;
       this.djPais = djPais;
       this.djEstado = djEstado;
       this.djNomeSite = djNomeSite;
       this.djDataCadastro = djDataCadastro;
    }
   
     @Id 

    
    @Column(name="dj_idFornecedor", unique=true, nullable=false)
    public int getDjIdFornecedor() {
        return this.djIdFornecedor;
    }
    
    public void setDjIdFornecedor(int djIdFornecedor) {
        this.djIdFornecedor = djIdFornecedor;
    }

    
    @Column(name="dj_nome", nullable=false, length=50)
    public String getDjNome() {
        return this.djNome;
    }
    
    public void setDjNome(String djNome) {
        this.djNome = djNome;
    }

    
    @Column(name="dj_cnpj", nullable=false, length=18)
    public String getDjCnpj() {
        return this.djCnpj;
    }
    
    public void setDjCnpj(String djCnpj) {
        this.djCnpj = djCnpj;
    }

    
    @Column(name="dj_rg", nullable=false, length=12)
    public String getDjRg() {
        return this.djRg;
    }
    
    public void setDjRg(String djRg) {
        this.djRg = djRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dj_dataNascimento", length=10)
    public Date getDjDataNascimento() {
        return this.djDataNascimento;
    }
    
    public void setDjDataNascimento(Date djDataNascimento) {
        this.djDataNascimento = djDataNascimento;
    }

    
    @Column(name="dj_email", nullable=false, length=80)
    public String getDjEmail() {
        return this.djEmail;
    }
    
    public void setDjEmail(String djEmail) {
        this.djEmail = djEmail;
    }

    
    @Column(name="dj_telefone", length=14)
    public String getDjTelefone() {
        return this.djTelefone;
    }
    
    public void setDjTelefone(String djTelefone) {
        this.djTelefone = djTelefone;
    }

    
    @Column(name="dj_endereco", nullable=false, length=50)
    public String getDjEndereco() {
        return this.djEndereco;
    }
    
    public void setDjEndereco(String djEndereco) {
        this.djEndereco = djEndereco;
    }

    
    @Column(name="dj_cidade", nullable=false, length=50)
    public String getDjCidade() {
        return this.djCidade;
    }
    
    public void setDjCidade(String djCidade) {
        this.djCidade = djCidade;
    }

    
    @Column(name="dj_bairro", nullable=false, length=30)
    public String getDjBairro() {
        return this.djBairro;
    }
    
    public void setDjBairro(String djBairro) {
        this.djBairro = djBairro;
    }

    
    @Column(name="dj_cep", nullable=false, length=9)
    public String getDjCep() {
        return this.djCep;
    }
    
    public void setDjCep(String djCep) {
        this.djCep = djCep;
    }

    
    @Column(name="dj_pais", nullable=false, length=20)
    public String getDjPais() {
        return this.djPais;
    }
    
    public void setDjPais(String djPais) {
        this.djPais = djPais;
    }

    
    @Column(name="dj_estado", nullable=false, length=50)
    public String getDjEstado() {
        return this.djEstado;
    }
    
    public void setDjEstado(String djEstado) {
        this.djEstado = djEstado;
    }

    
    @Column(name="dj_nomeSite", length=50)
    public String getDjNomeSite() {
        return this.djNomeSite;
    }
    
    public void setDjNomeSite(String djNomeSite) {
        this.djNomeSite = djNomeSite;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dj_dataCadastro", length=10)
    public Date getDjDataCadastro() {
        return this.djDataCadastro;
    }
    
    public void setDjDataCadastro(Date djDataCadastro) {
        this.djDataCadastro = djDataCadastro;
    }

}


