package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DjProdutos generated by hbm2java
 */
@Entity
@Table(name="dj_produtos"
    ,catalog="dj_sistemadevendasperfume_daniel"
)
public class DjProdutos  implements java.io.Serializable {


     private int djIdProdutos;
     private String djNome;
     private BigDecimal djPreco;
     private String djDescricao;
     private String djAvaliacao;
     private String djNomeDaFlor;
     private String djMaterial;
     private Set djComprasProdutoses = new HashSet(0);

    public DjProdutos() {
    }

	
    public DjProdutos(int djIdProdutos, String djNome, BigDecimal djPreco, String djDescricao, String djAvaliacao, String djNomeDaFlor, String djMaterial) {
        this.djIdProdutos = djIdProdutos;
        this.djNome = djNome;
        this.djPreco = djPreco;
        this.djDescricao = djDescricao;
        this.djAvaliacao = djAvaliacao;
        this.djNomeDaFlor = djNomeDaFlor;
        this.djMaterial = djMaterial;
    }
    public DjProdutos(int djIdProdutos, String djNome, BigDecimal djPreco, String djDescricao, String djAvaliacao, String djNomeDaFlor, String djMaterial, Set djComprasProdutoses) {
       this.djIdProdutos = djIdProdutos;
       this.djNome = djNome;
       this.djPreco = djPreco;
       this.djDescricao = djDescricao;
       this.djAvaliacao = djAvaliacao;
       this.djNomeDaFlor = djNomeDaFlor;
       this.djMaterial = djMaterial;
       this.djComprasProdutoses = djComprasProdutoses;
    }
   
     @Id 

    
    @Column(name="dj_idProdutos", unique=true, nullable=false)
    public int getDjIdProdutos() {
        return this.djIdProdutos;
    }
    
    public void setDjIdProdutos(int djIdProdutos) {
        this.djIdProdutos = djIdProdutos;
    }

    
    @Column(name="dj_nome", nullable=false, length=50)
    public String getDjNome() {
        return this.djNome;
    }
    
    public void setDjNome(String djNome) {
        this.djNome = djNome;
    }

    
    @Column(name="dj_preco", nullable=false, precision=10)
    public BigDecimal getDjPreco() {
        return this.djPreco;
    }
    
    public void setDjPreco(BigDecimal djPreco) {
        this.djPreco = djPreco;
    }

    
    @Column(name="dj_descricao", nullable=false)
    public String getDjDescricao() {
        return this.djDescricao;
    }
    
    public void setDjDescricao(String djDescricao) {
        this.djDescricao = djDescricao;
    }

    
    @Column(name="dj_avaliacao", nullable=false, length=45)
    public String getDjAvaliacao() {
        return this.djAvaliacao;
    }
    
    public void setDjAvaliacao(String djAvaliacao) {
        this.djAvaliacao = djAvaliacao;
    }

    
    @Column(name="dj_nome_da_flor", nullable=false, length=45)
    public String getDjNomeDaFlor() {
        return this.djNomeDaFlor;
    }
    
    public void setDjNomeDaFlor(String djNomeDaFlor) {
        this.djNomeDaFlor = djNomeDaFlor;
    }

    
    @Column(name="dj_material", nullable=false, length=45)
    public String getDjMaterial() {
        return this.djMaterial;
    }
    
    public void setDjMaterial(String djMaterial) {
        this.djMaterial = djMaterial;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="djProdutos")
    public Set getDjComprasProdutoses() {
        return this.djComprasProdutoses;
    }
    
    public void setDjComprasProdutoses(Set djComprasProdutoses) {
        this.djComprasProdutoses = djComprasProdutoses;
    }




}


