package bean;
// Generated 11/10/2025 16:59:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DjUsuarios generated by hbm2java
 */
@Entity
@Table(name="dj_usuarios"
    ,catalog="dj_sistemadevendasperfume_daniel"
)
public class DjUsuarios  implements java.io.Serializable {


     private int djIdUsuarios;
     private String djNome;
     private String djApelido;
     private String djCpf;
     private Date djDataNascimento;
     private String djSenha;
     private int djNivel;
     private String djAtivo;

    public DjUsuarios() {
    }

	
    public DjUsuarios(int djIdUsuarios, String djNome, String djApelido, String djCpf, String djSenha, int djNivel, String djAtivo) {
        this.djIdUsuarios = djIdUsuarios;
        this.djNome = djNome;
        this.djApelido = djApelido;
        this.djCpf = djCpf;
        this.djSenha = djSenha;
        this.djNivel = djNivel;
        this.djAtivo = djAtivo;
    }
    public DjUsuarios(int djIdUsuarios, String djNome, String djApelido, String djCpf, Date djDataNascimento, String djSenha, int djNivel, String djAtivo) {
       this.djIdUsuarios = djIdUsuarios;
       this.djNome = djNome;
       this.djApelido = djApelido;
       this.djCpf = djCpf;
       this.djDataNascimento = djDataNascimento;
       this.djSenha = djSenha;
       this.djNivel = djNivel;
       this.djAtivo = djAtivo;

    }
   
     @Id 

    
    @Column(name="dj_idUsuarios", unique=true, nullable=false)
    public int getDjIdUsuarios() {
        return this.djIdUsuarios;
    }
    
    public void setDjIdUsuarios(int djIdUsuarios) {
        this.djIdUsuarios = djIdUsuarios;
    }

    
    @Column(name="dj_nome", nullable=false, length=50)
    public String getDjNome() {
        return this.djNome;
    }
    
    public void setDjNome(String djNome) {
        this.djNome = djNome;
    }

    
    @Column(name="dj_apelido", nullable=false, length=25)
    public String getDjApelido() {
        return this.djApelido;
    }
    
    public void setDjApelido(String djApelido) {
        this.djApelido = djApelido;
    }

    
    @Column(name="dj_cpf", nullable=false, length=14)
    public String getDjCpf() {
        return this.djCpf;
    }
    
    public void setDjCpf(String djCpf) {
        this.djCpf = djCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dj_dataNascimento", length=10)
    public Date getDjDataNascimento() {
        return this.djDataNascimento;
    }
    
    public void setDjDataNascimento(Date djDataNascimento) {
        this.djDataNascimento = djDataNascimento;
    }

    
    @Column(name="dj_senha", nullable=false, length=20)
    public String getDjSenha() {
        return this.djSenha;
    }
    
    public void setDjSenha(String djSenha) {
        this.djSenha = djSenha;
    }

    
    @Column(name="dj_nivel", nullable=false)
    public int getDjNivel() {
        return this.djNivel;
    }
    
    public void setDjNivel(int djNivel) {
        this.djNivel = djNivel;
    }

    
    @Column(name="dj_ativo", nullable=false, length=1)
    public String getDjAtivo() {
        return this.djAtivo;
    }
    
    public void setDjAtivo(String djAtivo) {
        this.djAtivo = djAtivo;
    }

    public void getDjIdUsuarios(int strToInt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


}


